### ISSUE TITLE
Make Video

### ISSUE THREAD

**Issue by swagkarna** [Ross1337/SMSBotBypass#1]
If you make a video it will be very usefull

**Comment by extrome1012199** [comment]
Thanx you 
Please help me

**Comment by Ross1337** [comment]
I could do a video, but, all the instructions are in the README

**Comment by Bangbang901** [comment]
> I could do a video, but, all the instructions are in the README

I understand but certain things are not that clear for people who are not advance in all this stuff. A video would help me too.
