### ISSUE TITLE
Hello my friend , can I buy a ready-made bot with installation from you ?

### ISSUE THREAD

**Issue by Userrryouil** [Ross1337/SMSBotBypass#121]

**Comment by beanvito7** [comment]
> Im not sure, if you mean a discordbot. if so i just created one a few month ago and just made the repo public. Its written in Python and include lot of stuff such as Buy Number, check for verificationcode, store apikeys, usernames, timestamp etc in a Database, send hidden embeds (only the author can see them others dont even notice that you ran a command)

Can I buy bro add my discord ondavid#9086

**Comment by beanvito7** [comment]
> Yes ?
Can I buy one already made bro add me on discord  ondavid#9086

**Comment by FeelsBadMan1** [comment]
> 
> 
> > Im not sure, if you mean a discordbot. if so i just created one a few month ago and just made the repo public. Its written in Python and include lot of stuff such as Buy Number, check for verificationcode, store apikeys, usernames, timestamp etc in a Database, send hidden embeds (only the author can see them others dont even notice that you ran a command)
> 
> Can I buy bro add my discord ondavid#9086

Im not quite sure for what you want to pay. I have the soucecode from the bot public avaible on my reponsetory you dont need to buy anything just download the files (you also can take a look in the soucecode to see that there is no malware etc) and then just run the main.py but before you would need to edit config.jsonhowever i send you a dm on discord
