### ISSUE TITLE
{"error":"Not found, or bad request method."}

### ISSUE THREAD

**Issue by abeed2** [Ross1337/SMSBotBypass#127]
<img width="960" alt="من دون عنوان" src="https://user-images.githubusercontent.com/78418437/139185151-1c602733-815c-4d32-9a90-5052513671bd.png">

(call not send and i try from website but this error show)
Twilio Upgraded
Port 1337 Open
*i am host bot from windows*
plz Help My Tele 
@iamch
Abed#9450

**Comment by Ross1337** [comment]
Try using insomnia the call route using POST method
