### ISSUE TITLE
error

### ISSUE THREAD

**Issue by djovertune** [Ross1337/SMSBotBypass#129]
hello im getting this error when im trying to call any phone number
![23](https://user-images.githubusercontent.com/92055197/139449521-57050fe4-a2cd-4c47-968a-8f4f3383243f.PNG)

**Comment by djovertune** [comment]
im now having this error. could you help, sorry for all the trouble
![ttt](https://user-images.githubusercontent.com/92055197/139502638-a3d13abc-93ed-4db9-a24b-b0b3071acbd9.PNG)

**Comment by Ross1337** [comment]
Send your config.js file

**Comment by djovertune** [comment]
Can you add me on telegram
Telegram: djovertune
