### ISSUE TITLE
Can't get code back from call

### ISSUE THREAD

**Issue by MigthyMike** [Ross1337/SMSBotBypass#13]
I set up the api and the discord bot and I can make a call and then type the code but nothing is returned. Am I missing something or is it a bug ? Ps I tried with google

**Comment by Bangbang901** [comment]
I think you need to pay for the twilio number. I have the same issue. When i run the !call command, it says that it is calling but i never get a response back from the bot

**Comment by Jackbent99** [comment]
Did you try with upgrade account?

**Comment by MigthyMike** [comment]
so is the upgrade required for that ?

**Comment by Bangbang901** [comment]
I think you need to pay like 20$ on twilio. I didn’t bought it yet i was waiting to be sure that this was the problem.

**Comment by jamesdaniel12** [comment]
MightMike or Bangbang901 were any of you able to solve this issue and get the bot working/ dm me on tele @ZayHQ

**Comment by iProgeny** [comment]
> I set up the api and the discord bot and I can make a call and then type the code but nothing is returned. Am I missing something or is it a bug ? Ps I tried with google

How do i open port for apiurl:?? Can someone please help me with this?? that's my last error and i can't figure out how, i tried many ways but i still get "ECONNREFUSED" when i send an command "!call" to the bot soo it wont work properly since i probably don't have a port for the bot..

**Comment by Ross1337** [comment]
You need to upgrade your twilio account before making calls.
