### ISSUE TITLE
Bro Check This Error 

### ISSUE THREAD

**Issue by MohamdHasan963** [Ross1337/SMSBotBypass#133]
Bro can you check this error in my ?

![Screenshot 2021-10-31 233922](https://user-images.githubusercontent.com/85138407/139602074-6394abd2-fdd9-482e-8cd6-87caeb935b9b.png)

**Comment by Ross1337** [comment]
You're in the wrong directory

**Comment by pulcinella1312** [comment]
@Ross1337 Ross1337 where i can contact you brother asap

**Comment by Ross1337** [comment]
Give me your telegram
