### ISSUE TITLE
Error Help

### ISSUE THREAD

**Issue by tiqula** [Ross1337/SMSBotBypass#134]
https://gyazo.com/7ddc4608b2b0434de1f01921e7ad3cb3

what does this mean? how ro fix it?

**Comment by Ross1337** [comment]
Send your config.js file

**Comment by tiqula** [comment]
can you hit me up on discord @ Tiqula#0180

**Comment by Ross1337** [comment]
Give me your telegram

**Comment by tiqula** [comment]
@faybolovebins is my telegram

**Comment by tiqula** [comment]
did ever u hit me up on telegram?
