### ISSUE TITLE
calls arent going through

### ISSUE THREAD

**Issue by Kyeles** [Ross1337/SMSBotBypass#139]
https://gyazo.com/df15df85c615fa8df6634e08fada2cd7

calls are not going through with my upgraded twilio account. here is my config.js format, i have added "*" To hide my information.

module.exports = {
    setupdone: 'true',

    /**
     * Informations à propos du compte Twilio
     */
    accountSid: 'ACd*******452f3db0',
    authToken: 'ceb9e411024079ae******',
    callerid: '3203907263',

    /**
     * Informations à propos de l'API
     */
    apipassword: 'bktz4aL2o*******rhQ6nIa9I',
    serverurl: 'http://198.14*******:1337',

**Comment by Ross1337** [comment]
There should be a "+" in front of your callerid

**Comment by Kyeles** [comment]
> There should be a "+" in front of your calleriid"

Is callerid the phone number on my twilio account?

Also am I doing "+" or "+1" ?

**Comment by Ross1337** [comment]
Instead of callerid: '3203907263', it should be callerid: '+3203907263',
