### ISSUE TITLE
I need help Sir

### ISSUE THREAD

**Issue by troublz** [Ross1337/SMSBotBypass#146]
Hi, please help me..
Why otp not received to my discord? 
Please..my telegram @Troublz

thanks,

![image](https://user-images.githubusercontent.com/93849579/140631103-5905356e-d2a6-42f8-9f72-fab3b986bfcc.jpeg)

**Comment by wrldslife** [comment]
OTP bot is only if the other phone number answers :D

**Comment by troublz** [comment]
Yes, I know.. but it i tru with my phone number.. but no call came to my number 😃
