### ISSUE TITLE
 Uncaught AssertionError: expected { Object (error) } to not have property 'error'

### ISSUE THREAD

**Issue by betrayed-osu** [Ross1337/SMSBotBypass#151]
Hey, could you help me for this error please ? 
![image](https://user-images.githubusercontent.com/75703115/141309534-d4523669-979e-4d65-8715-975ef680df61.png)

**Comment by Ross1337** [comment]
Hello, give me your telegram

**Comment by betrayed-osu** [comment]
> Hello, give me your telegram

https://t.me/betrayed7777
