### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ArooX11** [Ross1337/SMSBotBypass#153]
yo, I can't integrate the discord bot even though I have followed all the steps, can you help me or put your bot in my discord pls?

**Comment by Ross1337** [comment]
Hello, give me your telegram

**Comment by ArooX11** [comment]
Somi L , my number : 0769532417

**Comment by ArooX11** [comment]
SomiL71

**Comment by Dramzx69** [comment]
> Bonjour, donnez-moi votre télégramme

You can add me : @ARI69420 
i have a problem when i config this
