### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by outofmymine** [Ross1337/SMSBotBypass#171]
![image](https://user-images.githubusercontent.com/83163716/142654694-0ec61959-ee4c-46f3-a2e6-d9d0ac2ba517.png)
sir why i dont have premission

**Comment by outofmymine** [comment]
https://t.me/Ayamjantan97 my telegram please help me dude

**Comment by Ross1337** [comment]
![image](https://user-images.githubusercontent.com/45340378/142663148-5c21355c-bebe-491c-a6b9-b8851282a698.png)

**Comment by AnaPointG** [comment]
> ![image](https://user-images.githubusercontent.com/45340378/142663148-5c21355c-bebe-491c-a6b9-b8851282a698.png)
iam not a robot and have the same problem :(

**Comment by Ross1337** [comment]
>

Use the upgrade command

**Comment by jockrx** [comment]
First created a server and and both yourself and the bot aswell with admin permissions for both users . Now use the upgrade method to upgrade yourself to admin in the server
