### ISSUE TITLE
Object error

### ISSUE THREAD

**Issue by NicsxSec** [Ross1337/SMSBotBypass#174]
Hi, i got some error when i run npm test

I've tried to solve it with google tutorial, but it won't solved
![Screenshot_195231](https://user-images.githubusercontent.com/55499177/142723227-93c1c816-3e20-4820-a5d5-81dd686f74cd.png)

**Comment by Ross1337** [comment]
Give me your telegram

**Comment by NicsxSec** [comment]
t.me/MugiwaraNic
