### ISSUE TITLE
i tried but dont receive any call

### ISSUE THREAD

**Issue by omaisloko** [Ross1337/SMSBotBypass#177]
This phone number is not good, a good one : 33612345678

**Comment by omaisloko** [comment]
call only for french

**Comment by omaisloko** [comment]
??

**Comment by Ross1337** [comment]
No ?

**Comment by ImShEthan** [comment]
Same for me. The bot is running without error and same for the api.

**Comment by Ross1337** [comment]
Bad configuration of the bot

**Comment by ImShEthan** [comment]
I don't see any error. I'm admin, no error in the console. The bot respond when i do !call, but i receive no call.
I can acces to the api with MYIP:1337 too.

**Comment by Ross1337** [comment]
What country are you trying to call ?

**Comment by ImShEthan** [comment]
France

**Comment by Ross1337** [comment]
Use insomnia to test your /call route and check if there is any error

**Comment by ImShEthan** [comment]
Do you have a telegram or a discord ?

**Comment by Ross1337** [comment]
Give me your telegram

**Comment by ImShEthan** [comment]
ShEthanBtw
