### ISSUE TITLE
error  call.js

### ISSUE THREAD

**Issue by williamsec999** [Ross1337/SMSBotBypass#178]
![node](https://user-images.githubusercontent.com/65137907/142779776-527dabe3-7093-4a0d-968f-f0ae55f7e974.jpg)
 need help https://t.me/unlockdone999

**Comment by jockrx** [comment]
Don't worry if your account isn't upgraded it's perfectly ok

**Comment by williamsec999** [comment]
I can't find the bot in discord, why is that?

**Comment by Ross1337** [comment]
??

**Comment by NicsxSec** [comment]
me too, i've upgraded my account, but its show the same error

**Comment by Ross1337** [comment]
Launch the api and check the /call route using insomnia

**Comment by ThePhyscoD** [comment]
How can i lunch the api


Sent from the all new AOL app for iOS


On Saturday, November 27, 2021, 6:31 AM, Ross ***@***.***> wrote:




Launch the api and check the /call route using insomnia

**Comment by ThePhyscoD** [comment]
Show me how


Sent from the all new AOL app for iOS


On Saturday, November 27, 2021, 6:31 AM, Ross ***@***.***> wrote:




Launch the api and check the /call route using insomnia

**Comment by Ross1337** [comment]
Look on google ?
