### ISSUE TITLE
SMS bot bypass

### ISSUE THREAD

**Issue by sicarios666** [Ross1337/SMSBotBypass#179]
Bonjour, je suis très intéressé par le code que vous avez publié 
Mais je comprends pas trop
Quel logiciel il faut pour ouvrir les codes, si vous pouvez m'aider sa serais super gentil merci 😉

**Comment by Ross1337** [comment]
Bonjour, ouvrir les codes ?

**Comment by sicarios666** [comment]
Oui pour ouvrir les codes est bien paramétrer comme il faut

**Comment by sicarios666** [comment]
Pour que le logiciel soit prêt à être utilisé sans problème

**Comment by Ross1337** [comment]
Lis le readme

**Comment by sicarios666** [comment]
Justement je comprends pas
Je c'est pas ou commencer 
Il faut installer sqlite ou autre chose justement pour paramétrer le bot
Merci en tout cas m'aider c'est gentil frère

**Comment by Ross1337** [comment]
![image](https://user-images.githubusercontent.com/45340378/143326159-2b331329-1be2-4398-b28f-896ea8ccbb2b.png)
Suffit de lire

**Comment by sicarios666** [comment]
Y a moyen que tu me fasse une vidéo en rapide pour que je comprenne puis que tu me l'envoie par mail stp si sa te dérange pas car j'aimerais trop l'utiliser, je recherche sa depuis longtemps, merci pour ton aide 🙏🏽

**Comment by DexterTech111** [comment]
¿Alguien tiene el número twilio en español?

**Comment by DexterTech111** [comment]
tengo la versión php de otpbot conectada a telegram, buscando twilio en español

**Comment by DexterTech111** [comment]
> Bonjour, je suis très intéressé par le code que vous avez publié
> Mais je comprends pas trop
> Quel logiciel il faut pour ouvrir les codes, si vous pouvez m'aider sa serais super gentil merci

Tengo la versión PHP, mucho más simple de entender para los principiantes. solo necesito twilio español

**Comment by doncorleonelh47** [comment]
Do you have English audio files you can share ?

**Comment by sicarios666** [comment]
@DexterTech111 puedes enviarme la version php?

**Comment by DexterTech111** [comment]
> Do you have English audio files you can share ?
i did'nt use audio file, i used Text-to-speech TwiML verb. so it reads the text instead of playing audio. i just need spain twilio number

**Comment by DexterTech111** [comment]
> puedes enviarme la version php?
okay, @DextertechV is my telegram

**Comment by sicarios666** [comment]
sorry I only have French number
you can share the php file to me please? 🙏🏽

**Comment by williamsec999** [comment]
> tengo la versión php de otpbot conectada a telegram, buscando twilio en español

Hola tengo

**Comment by YoungMoney01** [comment]
Rose please message me on telegram @Iam_imotal
