### ISSUE TITLE
Problem with Discord OTP Bot..

### ISSUE THREAD

**Issue by iProgeny** [Ross1337/SMSBotBypass#18]
Nice bot

**Comment by mrgetdough123** [comment]
> Nice bot

It worked for you?

**Comment by iProgeny** [comment]
> > Nice bot
> 
> It worked for you?

How do i open port for apiurl:?? Can someone please help me with this?? that's my last error and i can't figure out how, i tried many ways but i still get "ECONNREFUSED" when i send an command "!call" to the bot soo it wont work properly since i probably don't have a port for the bot.. That's my last and only problem to make it work :/

**Comment by MinedAnemone34** [comment]
> > > Nice bot
> > 
> > 
> > It worked for you?
> 
> How do i open port for apiurl:?? Can someone please help me with this?? that's my last error and i can't figure out how, i tried many ways but i still get "ECONNREFUSED" when i send an command "!call" to the bot soo it wont work properly since i probably don't have a port for the bot.. That's my last and only problem to make it work :/

which service do you use?

**Comment by Saymon160908** [comment]
> > > > Nice bot
> > > 
> > > 
> > > It worked for you?
> > 
> > 
> > How do i open port for apiurl:?? Can someone please help me with this?? that's my last error and i can't figure out how, i tried many ways but i still get "ECONNREFUSED" when i send an command "!call" to the bot soo it wont work properly since i probably don't have a port for the bot.. That's my last and only problem to make it work :/
> 
> which service do you use?

hey please help me out idk how to do set up my dscord is Vortax#3334

**Comment by Ross1337** [comment]
Just read the readme.
