### ISSUE TITLE
can anybody help me

### ISSUE THREAD

**Issue by lucy2000** [Ross1337/SMSBotBypass#180]
dm me on discord BlitzOTP#5873 i have everything setup but can't port forward and i get this error 1) 

Call.js
       /call POST
         it should return the callSid : everything's fine:
     Uncaught AssertionError: expected { Object (error) } to not have property 'error'

**Comment by kadolis** [comment]
I can help you troubleshoot this issue, hmu on telegram @podecinco

**Comment by Ross1337** [comment]
> 

Give me your telegram

**Comment by lucy2000** [comment]
give  me yours am currently out atm

**Comment by Ross1337** [comment]
Give me yours

**Comment by DexterTech111** [comment]
> > 
> 
> Give me your telegram

bro, i need a spanish twilio number,

**Comment by lucy2000** [comment]
do you have the english version ?

**Comment by Ross1337** [comment]
Give me your telegram

**Comment by lucy2000** [comment]
@Ross1337 i gave you my discord name Jesus Said No#5530

**Comment by ThePhyscoD** [comment]
Me???


Sent from the all new AOL app for iOS


On Thursday, November 25, 2021, 3:46 PM, Ross ***@***.***> wrote:




Give me your telegram

**Comment by Ross1337** [comment]
> Me??? Sent from the all new AOL app for iOS On Thursday, November 25, 2021, 3:46 PM, Ross ***@***.***> wrote: Give me your telegram — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

?
