### ISSUE TITLE
New Audio files 

### ISSUE THREAD

**Issue by jquinones8** [Ross1337/SMSBotBypass#181]
i see the files should be mp3 but whats exacly the right format

i test with mp3 and dont work

test with mpeg and rename as mp3 and works but audio its wrong

another question how must last the mp3 audio, 1 minute or less? 

Thanks !

**Comment by kadolis** [comment]
Needs to be .mp3! I've changed no problems when I made English translation package. If you need help hmu @podecinco on tl

**Comment by jquinones8** [comment]
thats right was my stupid voip number with bad conection, everything its working thanks :D
