### ISSUE TITLE
Bot discord " You don't have the permissions to use this command. Please ask help to an admin. "

### ISSUE THREAD

**Issue by am-523** [Ross1337/SMSBotBypass#186]
<img width="631" alt="Screen Shot 2021-11-25 at 13 17 48" src="https://user-images.githubusercontent.com/61135648/143389754-1082c479-1837-4aff-a1d1-a02dc0e13036.png">

**Comment by lucy2000** [comment]
create a a role "admin" with admin permissions and then the cumane-bot role to admin and the !help then use !user setadmin @whatever the bot is then !secret your secret password @whatever the bot is
boom finished

**Comment by am-523** [comment]
thx dude , is working  🔥 

why every time there is a call, there is an error message?

**Comment by Ross1337** [comment]
Where ?

**Comment by lucy2000** [comment]
you need to upgrade your twilio account

**Comment by lucy2000** [comment]
@Ross1337 heres my discord Jesus Said No#5530

**Comment by Ross1337** [comment]
Give me your telegram

**Comment by ThePhyscoD** [comment]
dGhos_t


Sent from the all new AOL app for iOS


On Saturday, November 27, 2021, 6:29 AM, Ross ***@***.***> wrote:




Give me your telegram

**Comment by am-523** [comment]
> Give me your telegram

https://t.me/uncle_jacki

**Comment by Carlozxrootrt** [comment]
> create a a role "admin" with admin permissions and then the cumane-bot role to admin and the !help then use !user setadmin @whatever the bot is then !secret your secret password @whatever the bot is boom finished

it's not work for now ?
