### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by aliferik02** [Ross1337/SMSBotBypass#191]
apiurl and apipassword, how to get it? And scret password?

**Comment by Ross1337** [comment]
You choose the secret password, the api password is automaticly generated and the api url is http://yourip:1337

**Comment by aliferik02** [comment]
![Screenshot_2021-11-28-18-06-59-860_com termux](https://user-images.githubusercontent.com/39854087/143791723-64f99e9e-2241-48fc-8429-9e8eb6b3687a.jpg)
Error, module cjs loader

**Comment by YoungMoney01** [comment]
> 

Please DM on telegram for God sake I have something for you to donate also @Iam_imotal

**Comment by Ross1337** [comment]
> 

Npm i

**Comment by Ross1337** [comment]
> > 
> 
> Please DM on telegram for God sake I have something for you to donate also @Iam_imotal

Done

**Comment by Ross1337** [comment]
![image](https://user-images.githubusercontent.com/45340378/143913476-68e60d6c-93d9-44c4-9204-9451a39fa2a8.png)
