### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:1337     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {

### ISSUE THREAD

**Issue by am-523** [Ross1337/SMSBotBypass#193]
<img width="743" alt="Screen Shot 2021-11-29 at 17 39 28" src="https://user-images.githubusercontent.com/61135648/143853287-7521b657-5a2b-441e-916b-e7e931bb6532.png">

<img width="532" alt="Screen Shot 2021-11-29 at 17 40 06" src="https://user-images.githubusercontent.com/61135648/143853389-620d3a0c-6b90-4ecf-9179-d282d28fddb4.png">

**Comment by am-523** [comment]
<img width="1335" alt="Screen Shot 2021-11-29 at 18 11 25" src="https://user-images.githubusercontent.com/61135648/143857890-0ae81016-15dd-46b2-ab84-6d91ffef50a6.png">

**Comment by Ross1337** [comment]
Your apiurl should be your public ip not a localhost

**Comment by am-523** [comment]
where i buy apiurl public ?

**Comment by Ross1337** [comment]
There is no need to buy, juste put your public ip

**Comment by Carlozxrootrt** [comment]
maybe u can run with VPS brother
