### ISSUE TITLE
facing issue with bot/discord config.js file

### ISSUE THREAD

**Issue by zumarcrm** [Ross1337/SMSBotBypass#196]
I need help to fill values for these in config.js files

module.exports = {
    apiurl: 'http://localhost:1337',
    apipassword: '',

    discordtoken: '',
    discordprefix: '!',
    secretpassword: 'ChAnGeThIsWiThYoUrPaSsWoRdNoW!',
    botuser_rolename: 'Bot User',
    admin_rolename: 'Admin'
};

anybody guide me in this regard.

Thanks

**Comment by Ross1337** [comment]
Hello,
Apiurl = http://yourpublicip:1337
Apipassword is automaticly generated when you start the api

**Comment by Carlozxrootrt** [comment]
secretpassword: 'ChAnGeThIsWiThYoUrPaSsWoRdNoW!', 

your password bot discord

**Comment by zumarcrm** [comment]
Hi Guys,
Thanks for the answer,

Can you please tell me what the value for this? 
**discordtoken: '',**

how i can get discordtoken: '' value?

**Comment by am-523** [comment]
add " ! "

**Comment by Ross1337** [comment]
In your discord application

**Comment by zumarcrm** [comment]
> In your discord application

Ross can you help me to setup OTP app by using your source code?

**Comment by Ross1337** [comment]
Give me your telegram
