### ISSUE TITLE
help me brother 

### ISSUE THREAD

**Issue by Carlozxrootrt** [Ross1337/SMSBotBypass#197]
![image](https://user-images.githubusercontent.com/95312031/144113625-658fe7da-342d-4ee6-a002-177622333b40.png)

why brother :(

**Comment by Ross1337** [comment]
Use the !secret command before

**Comment by Carlozxrootrt** [comment]
> 

![image](https://user-images.githubusercontent.com/95312031/144123249-5892ea3b-668e-4927-bfff-e4fe3262f1e7.png)
  ihave another :(
