### ISSUE TITLE
Triead password secret :( 

### ISSUE THREAD

**Issue by Carlozxrootrt** [Ross1337/SMSBotBypass#198]
![image](https://user-images.githubusercontent.com/95312031/144153752-5e7dcb06-a688-49ac-8e42-36c31b5026e0.png)

someone please help me

**Comment by xcoder0day** [comment]
AOKWAWOKAWKOAWKO RUN NPM I NYA BG MA NPM START BG JAGO baru bisa add user bot sama kau jadi admin
