### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by extrome1012199** [Ross1337/SMSBotBypass#2]
Besoin d’aide pour un truc à propos de sa

**Comment by Ross1337** [comment]
Dit moi

**Comment by extrome1012199** [comment]
A tu un telegram afin d’avoir une réponse plus rapidement stp ?

**Comment by extrome1012199** [comment]
Ou discord ?

**Comment by extrome1012199** [comment]
Tien mon discord extrome12345#1778
Ajoute moi stp
