### ISSUE TITLE
port open issue

### ISSUE THREAD

**Issue by iProgeny** [Ross1337/SMSBotBypass#20]
How do i open port for apiurl:?? Can someone please help me with this?? that's my last error and i can't figure out how, i tried many ways but i still get "ECONNREFUSED" when i send an command "!call" to the bot soo it wont work properly since i probably don't have a port for the bot..

**Comment by Ross1337** [comment]
Already responded on others issues, https://www.youtube.com/watch?v=JuUTEZvFmHY
