### ISSUE TITLE
Bot discord " Permissions You don't have the permissions to use this command. Please ask help to an admin. "

### ISSUE THREAD

**Issue by carlozxroot** [Ross1337/SMSBotBypass#200]
![image](https://user-images.githubusercontent.com/56260201/144376564-017986b0-bc6f-4d83-bb9d-52bc2ede3a53.png)

Bot discord " Permissions You don't have the permissions to use this command. Please ask help to an admin. "

i'm try for create some secret password and can't 

how to fix it ..

**Comment by xcoder0day** [comment]
masuk ke DS config bang , ntr baru kasih secret id sama user bot sama kau di masukin jadi admin dlu

**Comment by carlozxroot** [comment]
> masuk ke DS config bang , ntr baru kasih secret id sama user bot sama kau di masukin jadi admin dlu

mksudnya gimana tuh ? telegram @https://t.me/tinksky telergam coba

**Comment by carlozxroot** [comment]
> masuk ke DS config bang , ntr baru kasih secret id sama user bot sama kau di masukin jadi admin dlu

done brother thanks :D
