### ISSUE TITLE
TypeError [INVALID_TYPE]: Supplied roles is not an Array or Collection of Roles or Snowflakes.     at GuildMemberRoleManager.remove (C:\Users\HOME\Downloads\SMSBotBypass-master\SMSBotBypass-master\SMSBotBypass-master\bots\discord\node_modules\discord.js\src\managers\GuildMemberRoleManager.js:122:15)     at Statement.<anonymous> (C:\Users\HOME\Downloads\SMSBotBypass-master\SMSBotBypass-master\SMSBotBypass-master\bots\discord\commands\user.js:149:38)     at Statement.replacement (C:\Users\HOME\Downloads\SMSBotBypass-master\SMSBotBypass-master\SMSBotBypass-master\bots\discord\node_modules\sqlite3\lib\trace.js:25:27) {   [Symbol(code)]: 'INVALID_TYPE'

### ISSUE THREAD

**Issue by xcoder0day** [Ross1337/SMSBotBypass#201]
any idea to solved admin?

**Comment by xcoder0day** [comment]
TypeError [INVALID_TYPE]: Supplied roles is not an Array or Collection of Roles or Snowflakes.
    at GuildMemberRoleManager.remove (C:\Users\HOME\Downloads\SMSBotBypass-master\SMSBotBypass-master\SMSBotBypass-master\bots\discord\node_modules\discord.js\src\managers\GuildMemberRoleManager.js:122:15)
    at Statement.<anonymous> (C:\Users\HOME\Downloads\SMSBotBypass-master\SMSBotBypass-master\SMSBotBypass-master\bots\discord\commands\user.js:149:38)
    at Statement.replacement (C:\Users\HOME\Downloads\SMSBotBypass-master\SMSBotBypass-master\SMSBotBypass-master\bots\discord\node_modules\sqlite3\lib\trace.js:25:27) {
  [Symbol(code)]: 'INVALID_TYPE'

**Comment by carlozxroot** [comment]
> TypeError [INVALID_TYPE]: Supplied roles is not an Array or Collection of Roles or Snowflakes. at GuildMemberRoleManager.remove (C:\Users\HOME\Downloads\SMSBotBypass-master\SMSBotBypass-master\SMSBotBypass-master\bots\discord\node_modules\discord.js\src\managers\GuildMemberRoleManager.js:122:15) at Statement. (C:\Users\HOME\Downloads\SMSBotBypass-master\SMSBotBypass-master\SMSBotBypass-master\bots\discord\commands\user.js:149:38) at Statement.replacement (C:\Users\HOME\Downloads\SMSBotBypass-master\SMSBotBypass-master\SMSBotBypass-master\bots\discord\node_modules\sqlite3\lib\trace.js:25:27) { [Symbol(code)]: 'INVALID_TYPE'

punya lu udah parsing ijo semua belum waktu test NPM ?

**Comment by xcoder0day** [comment]
> > TypeError [INVALID_TYPE]: Supplied roles is not an Array or Collection of Roles or Snowflakes. at GuildMemberRoleManager.remove (C:\Users\HOME\Downloads\SMSBotBypass-master\SMSBotBypass-master\SMSBotBypass-master\bots\discord\node_modules\discord.js\src\managers\GuildMemberRoleManager.js:122:15) at Statement. (C:\Users\HOME\Downloads\SMSBotBypass-master\SMSBotBypass-master\SMSBotBypass-master\bots\discord\commands\user.js:149:38) at Statement.replacement (C:\Users\HOME\Downloads\SMSBotBypass-master\SMSBotBypass-master\SMSBotBypass-master\bots\discord\node_modules\sqlite3\lib\trace.js:25:27) { [Symbol(code)]: 'INVALID_TYPE'
> 
> punya lu udah parsing ijo semua belum waktu test NPM ?

udah

**Comment by Ross1337** [comment]
Bad roles configuration
