### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by rudalbekas** [Ross1337/SMSBotBypass#209]
Permissions
You don't have the permissions to use this command. Please ask help to an admin.

how to solve it?

**Comment by Ross1337** [comment]
Use the !secret command

**Comment by rudalbekas** [comment]
Bad first argument
The first argument needs to be your secret password, example : !secret yoursecretpass @example

**Comment by rudalbekas** [comment]
caller id filled with what ?

**Comment by Ross1337** [comment]
By your twillio caller id

**Comment by rudalbekas** [comment]
where to check the celler id?

**Comment by rudalbekas** [comment]
plz send your telegram bro

**Comment by rudalbekas** [comment]
or me telegram @useralert

**Comment by Ross1337** [comment]
Done
