### ISSUE TITLE
important

### ISSUE THREAD

**Issue by AllahChoseHamas** [Ross1337/SMSBotBypass#211]
can i add extra modules/scripts? for venmo, cashapp, coinbase etc?? if yes then how

**Comment by Ross1337** [comment]
Yes, add the mp3's in the voice folder

**Comment by GuymanZy3122** [comment]
> can i add extra modules/scripts? for venmo, cashapp, coinbase etc?? if yes then how

can you help me run the api cos i keep getting syntax error on cmd

**Comment by Ross1337** [comment]
Screen the error
