### ISSUE TITLE
PLEASE HOW TO FIX IT - TELEGRAM @DrizzyOficial

### ISSUE THREAD

**Issue by byDrizzy** [Ross1337/SMSBotBypass#213]
Call.js
    /call POST
      3) it should return an ERROR with "Please post all the informations needed." : we sent no post data
      4) it should return an ERROR with "Please post all the informations needed." : we sent 1 post data
      5) it should return an ERROR with "Please post all the informations needed." : we sent 2 post data
      6) it should return an ERROR with "The service wasn't recognised." : we sent 3 post data (but bad service)
      7) it should return an ERROR with "Bad phone number." : we sent 3 post data (but bad phone number)
      8) it should return the callSid : everything's fine

  Config.js
    twilio INFORMATIONS
      9) checking the twilio logins using the api : should allow to use it

![PNG SS BOT](https://user-images.githubusercontent.com/95592412/144770908-13a99991-9d3a-4349-ad2b-1a3883461785.png)

**Comment by Ross1337** [comment]
Did you filled your config.js file ?
