### ISSUE TITLE
bot start 

### ISSUE THREAD

**Issue by Banksss74** [Ross1337/SMSBotBypass#214]
having issue getting bot to start and run

**Comment by GuymanZy3122** [comment]
can't get api to run on cmd
kinda lost don't know if the bot really works
what can be done about it\

**Comment by Ross1337** [comment]
Give me your telegram

**Comment by Banksss74** [comment]
Jefe banks 3308007459 on tele

**Comment by GuymanZy3122** [comment]
ZY

**Comment by Gashkan** [comment]
> Give me your telegram

Chat me bro help me @Akusiapaoiii my username
