### ISSUE TITLE
Not receiving calls

### ISSUE THREAD

**Issue by polinated** [Ross1337/SMSBotBypass#216]
I'm trying to test the bot with my phone number, when I type .call it says its calling me, but on my phone I am not receiving any calls, how to fix this?

**Comment by Ross1337** [comment]
Screen your discord config.js file

**Comment by polinated** [comment]
> Screen your discord config.js file

![image](https://user-images.githubusercontent.com/95658990/145111408-756eb807-9c33-4c95-9e27-f26ed7af1a38.png)

**Comment by Ross1337** [comment]
Is your port 1337 open ?

**Comment by polinated** [comment]
> Is your port 1337 open ?

How do I know if its open how I do open it

**Comment by CreedoW** [comment]
On wifi configuration

> > Is your port 1337 open ?
> 
> How do I know if its open how I do open it
