### ISSUE TITLE
config error ? or need upgrade account twilio ?

### ISSUE THREAD

**Issue by talitharaha** [Ross1337/SMSBotBypass#217]
- npm test result : 
![image](https://user-images.githubusercontent.com/87280022/144972182-291aec81-26d9-4b3e-b6a9-90838dacee20.png)

- Is this working on trial akun Twilio ?
![image](https://user-images.githubusercontent.com/87280022/144972355-90d4912c-447b-4dd5-8d4e-91a0772bfb9e.png)

- OR I have wrong config ?
![image](https://user-images.githubusercontent.com/87280022/144972623-5bb02005-7ab4-4b89-b12b-c9afa4e53745.png)

**Comment by aamarkurniawan** [comment]
How u solved on this bro?

**Comment by talitharaha** [comment]
need twillio acount premium to solve.. if you want i have an account , with that balance

**Comment by talitharaha** [comment]
i dont have twilio account premium.
