### ISSUE TITLE
  1) Call.js/call POST

### ISSUE THREAD

**Issue by aamarkurniawan** [Ross1337/SMSBotBypass#220]
plz, if i not was here, contact me bro/sist on my telegram acc @aamarkurniawan

**Comment by aamarkurniawan** [comment]
Why bro?


  26 passing (5s)
  1 failing

  1) Call.js
       /call POST
         it should return the callSid : everything's fine:
     Uncaught AssertionError: expected { Object (error) } to not have property 'error'
      at C:\Users\muamm\SMSBotBypass\api\test\call.js:129:46
      at Test.Request.callback (node_modules\superagent\lib\node\index.js:716:12)
      at C:\Users\muamm\SMSBotBypass\api\node_modules\superagent\lib\node\index.js:916:18
      at IncomingMessage.<anonymous> (node_modules\superagent\lib\node\parsers\json.js:19:7)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by aamarkurniawan** [comment]
> _No description provided._



> Why bro?
> 
> 26 passing (5s) 1 failing
> 
> 1. Call.js
>    /call POST
>    it should return the callSid : everything's fine:
>    Uncaught AssertionError: expected { Object (error) } to not have property 'error'
>    at C:\Users\muamm\SMSBotBypass\api\test\call.js:129:46
>    at Test.Request.callback (node_modules\superagent\lib\node\index.js:716:12)
>    at C:\Users\muamm\SMSBotBypass\api\node_modules\superagent\lib\node\index.js:916:18
>    at IncomingMessage. (node_modules\superagent\lib\node\parsers\json.js:19:7)
>    at IncomingMessage.emit (node:events:402:35)
>    at endReadableNT (node:internal/streams/readable:1343:12)
>    at processTicksAndRejections (node:internal/process/task_queues:83:21)
![Screenshot (407)](https://user-images.githubusercontent.com/95725769/145128100-8d6f43ac-675b-4268-9a45-495e204837d0.png)

**Comment by Ross1337** [comment]
Added on tg.
