### ISSUE TITLE
Permissions :  You don't have the permissions to use this command. Please ask help to an admin.

### ISSUE THREAD

**Issue by CoreLine76** [Ross1337/SMSBotBypass#225]
Discord Bot : Permissions
You don't have the permissions to use this command. Please ask help to an admin.
---------
This is the error I got. how can i fix this error / 

I gave Bot Roles. However I still get the same error 
Pls help me Ross :)
Telegram : CoreLine76

**Comment by Ross1337** [comment]
Added.

**Comment by CoreLine76** [comment]
Ross Can you please help. It gives permission error, I can't run commands all the time.

**Comment by Ross1337** [comment]
Give me your telegram.
