### ISSUE TITLE
Bonjour at the start of the call

### ISSUE THREAD

**Issue by Kerar** [Ross1337/SMSBotBypass#226]
How do I get rid of the Bonjour at the start of the call? I'm trying to replace the french audio files with english ones but still says bonjour at the beginning but cant find the file for it.
Also the bot calls some numbers, but with other numbers nothing happens. Those numbers that don't go through don't appear in twilio call log either so for some reason the bot doesnt put it through 
If you have any suggestions let me know please.
add me on telegram please if possible to further discuss it: @KarverKapone

**Comment by Ross1337** [comment]
Added.
