### ISSUE TITLE
Error api doesnt work 

### ISSUE THREAD

**Issue by darksoul1310** [Ross1337/SMSBotBypass#228]
![image](https://user-images.githubusercontent.com/95855126/145383799-7dccb40b-9ebc-485a-9541-ba5cc7ed57df.png)

its show like this, but i dont receive any calls, 

But, when i do on test call its works.

feel free to contact me TELEGRAM : @aloyggwp

pls help me :) @Ross1337

**Comment by CreedoW** [comment]
go in api folder and do npm test, after paste screenshot here 
maybe I can help you

**Comment by darksoul1310** [comment]
![image](https://user-images.githubusercontent.com/95855126/145422898-bdd327e7-3999-4f4e-a1c0-2112ebf0358a.png)
@CreedoW

**Comment by Ross1337** [comment]
Added on tg.
