### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by brayed29** [Ross1337/SMSBotBypass#229]
how about this? 
if you can spare your time to help me, you can reach me via telegram @Brayed29. thank you

![image](https://user-images.githubusercontent.com/95856129/145425484-20450270-10ed-4b96-9621-69e57e84a9ac.png)

**Comment by ampaskopi999** [comment]
same problem bro  :(

**Comment by brayed29** [comment]
> same problem bro :(

iya tutor nya ambigu

**Comment by ampaskopi999** [comment]
lanjut pm bree kita devlop bareng buat nembuskan bank log us sama bypas amazon
https://t.me/Dx66vi7cvvick7eYzJjvvi88viv

**Comment by Ross1337** [comment]
Added on tg.
