### ISSUE TITLE
NOT RECIVE THE CALL FROM BOT

### ISSUE THREAD

**Issue by ampaskopi999** [Ross1337/SMSBotBypass#231]
MY BOT NOT CALL THE NUMBER
I DON'T GET ANY CALL INTO MY US PHONE NUMBER
ALWAYS STUCK ON THIS 

response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]

![Screenshot (22)](https://user-images.githubusercontent.com/95840232/145440181-d81116de-61c2-4025-a707-faf2f19d90b8.png)
![Screenshot (23)](https://user-images.githubusercontent.com/95840232/145440534-7d06c46d-d803-478c-830f-08b375654a59.png)
![Screenshot (24)](https://user-images.githubusercontent.com/95840232/145440545-165cd6ec-a288-47fb-a79f-1e921f9acb8b.png)
![Screenshot (25)](https://user-images.githubusercontent.com/95840232/145440549-66942cc2-e166-4be4-8a64-7ec8106dbcd4.png)

PLEASE HELP ME

**Comment by ampaskopi999** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/95840232/145479932-c37c8ecc-8516-40b7-ba88-8f4c6096c444.png)

if you get problem like this make sure your twilio account has been upgrade

**Comment by Ross1337** [comment]
Give me your telegram

**Comment by heykenz1** [comment]
> Give me your telegram

Sir cant you help me?

**Comment by Ross1337** [comment]
Give me your telegram again

**Comment by heykenz1** [comment]
> 

Kenzzz

**Comment by Ross1337** [comment]
Added
