### ISSUE TITLE
Help me Ross

### ISSUE THREAD

**Issue by CoreLine76** [Ross1337/SMSBotBypass#233]
Hello dear Ross.
The errors I get are listed below. Can you help me please
<img style="-webkit-user-select: none;margin: auto;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;" src="https://i.ibb.co/hdvzmhp/ross.png" width="897" height="505">
<img style="-webkit-user-select: none;margin: auto;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;" src="https://i.ibb.co/Mkj1fVM/screen2.png" width="897" height="505">
<img style="-webkit-user-select: none;margin: auto;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;" src="https://i.ibb.co/JxBXLyC/screen3.png" width="897" height="505">
<img style="-webkit-user-select: none;margin: auto;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;" src="https://i.ibb.co/yyp572F/screen4.png" width="897" height="505">
<img style="-webkit-user-select: none;margin: auto;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;" src="https://i.ibb.co/0q1fBxW/screen5.png" width="897" height="505">
<img style="-webkit-user-select: none;margin: auto;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;" src="https://i.ibb.co/phJY4mP/screen6.png" width="897" height="505">

**Comment by Ross1337** [comment]
Hello, give me your telegram
