### ISSUE TITLE
DON'T RECEIVE OTP AFTER SUCCESSFULLY MAKE A CALL IN

### ISSUE THREAD

**Issue by ampaskopi999** [Ross1337/SMSBotBypass#234]
please help me how to fix this my bot cannot get respon anything after incoming call , how to fix this, my bot just working to call the number and play the voice not get response anything 

![Screenshot (34)](https://user-images.githubusercontent.com/95840232/145573947-0fa31d96-b980-456a-b16c-cbf2ecf5ecc8.png)

**Comment by Ross1337** [comment]
Give me your telegram

**Comment by JigsawZX** [comment]
same problem

**Comment by Ross1337** [comment]
Give tg

**Comment by anonintellect** [comment]
Hello I have issues with the bot;
Please help me if possible, this is my Telegram ID:
@loonerwolf
