### ISSUE TITLE
i don't receveid call

### ISSUE THREAD

**Issue by JigsawZX** [Ross1337/SMSBotBypass#236]
I can launch the call with the sue discord command, but I don't receive the call on the phone.

Add me on telegram please ross: @ghonryk

**Comment by JigsawZX** [comment]
Si tu est français : je reçoit l'appel mais une femme parle en anglais et raccroche au bout de 3 seconde

in english : I receive the call but a woman speaks in English and hangs up after 3 seconds

**Comment by savagesssss** [comment]
jigsaw can u pm me to help me with setup ill pay u 1,750 bat if u help me my discord is wedontlikeyou#6332
