### ISSUE TITLE
Not sure what I’m doing wrong. Keep getting this error 

### ISSUE THREAD

**Issue by Jackkynou** [Ross1337/SMSBotBypass#239]
I’m confused at this point can someone help 
![image](https://user-images.githubusercontent.com/96230910/146336361-27e2101c-9b6f-4d17-ad93-3f8716ec72ac.jpg)

**Comment by Jackkynou** [comment]
Can someone please help I’ve been going at it for hours

**Comment by Jackkynou** [comment]
Telegram @justoce. Please help @Ross1337

**Comment by Ross1337** [comment]
Added
