### ISSUE TITLE
port and api URL problem

### ISSUE THREAD

**Issue by constantbruhmoment** [Ross1337/SMSBotBypass#24]
i dont know how to open a port and it says enter api url, api password in cd bots/discord/config.js

i got the api password in api/config.js but I dont know how to get API URL let me know
discord- constantbruhmoment#6184

**Comment by Ross1337** [comment]
Your API URL is the url where you have setup the call api. If this is on the same server, it will be localhost:yourports

**Comment by Ross1337** [comment]
My bad, it will be your ip:your ports , not localhost

**Comment by constantbruhmoment** [comment]
is it something related to ngrok?

**Comment by Ross1337** [comment]
You don't need to use ngrok.

**Comment by constantbruhmoment** [comment]
so what port do am i supposed to use

**Comment by constantbruhmoment** [comment]
and could you explain in details everything about opening the ports and twilio api in the readme

**Comment by Ross1337** [comment]
Just follow the read me or pay someone to install the bot. There is nothing complicated.

**Comment by constantbruhmoment** [comment]
dm me on discord constantbruhmoment#6184
