### ISSUE TITLE
Keep up the good job

### ISSUE THREAD

**Issue by xcon-daddy** [Ross1337/SMSBotBypass#240]
Wow amazing been waiting on this and I just now catching up. Thanks Ross1337...

**Comment by Jackkynou** [comment]
Can you help me set it up? He hasn’t responded an I’m stuck at basically the end

**Comment by Ross1337** [comment]
Give me your tg

**Comment by terrorboy2021** [comment]
Can you also help me out Ross1337? my telegram is @hofnar30

**Comment by terrorboy2021** [comment]
> Give me your tg

@Ross1337 my telegram is hofnar30

**Comment by Ross1337** [comment]
Added

**Comment by nmoneyballin** [comment]
Can you help me set this up I don't really kno what I'm doing ..I have kali li

**Comment by Ross1337** [comment]
Give me your telegram
