### ISSUE TITLE
I am getting an error

### ISSUE THREAD

**Issue by terrorboy2021** [Ross1337/SMSBotBypass#241]
Hi,

Great project! Can you help me out please? I am getting an error

**Comment by terrorboy2021** [comment]
test twilio passed the test (27). I also have the discord bot running and responding

**Comment by terrorboy2021** [comment]
![invalidpassword](https://user-images.githubusercontent.com/96310279/146593886-edbdbf9e-a326-4de3-a449-1adedb6ae95a.png)

**Comment by terrorboy2021** [comment]
![port1337](https://user-images.githubusercontent.com/96310279/146594879-14320da7-0065-45c2-9e13-e6b1207e97c3.png)

**Comment by terrorboy2021** [comment]
> ![port1337](https://user-images.githubusercontent.com/96310279/146594879-14320da7-0065-45c2-9e13-e6b1207e97c3.png)

Should it go trough IPv6? if not how do I change it? and will this solve my issue? thanks

**Comment by terrorboy2021** [comment]
![27passing](https://user-images.githubusercontent.com/96310279/146595277-89c92c0a-96db-4102-9399-98ad25fc08c7.png)

**Comment by Ross1337** [comment]
Hello, give me your tg

**Comment by bvm7x** [comment]
I have the same problem Is it help

**Comment by Ross1337** [comment]
Give me your tg
