### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by bigdreams-max** [Ross1337/SMSBotBypass#245]
H

**Comment by bigdreams-max** [comment]
This is my telegram 
@yungkhalifa02

**Comment by bigdreams-max** [comment]
![image](https://user-images.githubusercontent.com/70798232/146681693-072d0fdf-3073-45a9-a586-578e28ba0a93.jpeg)

**Comment by 0190342791072401740917904E9012740997199** [comment]
u need premium Twilio account

**Comment by bigdreams-max** [comment]
![image](https://user-images.githubusercontent.com/70798232/146683290-daad0581-5a52-440c-b9a9-5f19d9b1989b.jpeg)

**Comment by bigdreams-max** [comment]
I did it it worked without the premium account 
Now what next

**Comment by bigdreams-max** [comment]
I want to know how to find my discord bot token and also how to create discord roles and also how to add the bot to the discord server

**Comment by bigdreams-max** [comment]
![image](https://user-images.githubusercontent.com/70798232/146687340-917e8ba4-0b72-448f-ba5d-a9cde1f0d0d1.png)

**Comment by bigdreams-max** [comment]
I did it
Thanks

**Comment by bigdreams-max** [comment]
Now I want you to help me use it

**Comment by Ross1337** [comment]
What ?

**Comment by bigdreams-max** [comment]
![image](https://user-images.githubusercontent.com/70798232/146692291-929ebaef-ad50-46de-827f-b593e4fb15fd.png)

**Comment by bigdreams-max** [comment]
Help me

**Comment by Ross1337** [comment]
!secret
