### ISSUE TITLE
NEED ASSISTANCE

### ISSUE THREAD

**Issue by kryptonitehunter** [Ross1337/SMSBotBypass#247]
HI I NEED SOME ASSISTANCE FOR THE INSTALLATION @Ross1337 MY TG: kryptonitehunter

**Comment by idec1226** [comment]
If he winds up messaging you please help me out to

**Comment by Ross1337** [comment]
Hello, added

**Comment by bigmeech28** [comment]
ross can you add me on telegram bigmeech288 i need help getting this brother

**Comment by Ross1337** [comment]
Added
