### ISSUE TITLE
If anyone can help me set this up. It's confusing telegram @sammarou

### ISSUE THREAD

**Issue by sammaroi** [Ross1337/SMSBotBypass#249]
Someone please help @sammarou on telegram
@Ross1337

**Comment by Ross1337** [comment]
Added

**Comment by Pannuco** [comment]
Can you help me as well @Ross1337 my telegram is @pannuco, I set it up already just getting this error with npm test   Uncaught AssertionError: expected { Object (error) } to not have property 'error'

**Comment by Ross1337** [comment]
Added
