### ISSUE TITLE
it should return the callSid : everything's fine

### ISSUE THREAD

**Issue by KurwaBoy** [Ross1337/SMSBotBypass#25]
Uncaught AssertionError: expected { Object (error) } to not have property 'error'
Can anybody help me with this?
![image](https://user-images.githubusercontent.com/49104842/129425176-6467e5d8-61c9-451a-86cd-c3d1ce642e05.png)

**Comment by TyDrizzle** [comment]
Y

**Comment by Ross1337** [comment]
Have you upgraded your twilio account ?

**Comment by KurwaBoy** [comment]
No, not yet

**Comment by Ross1337** [comment]
Try to upgrade your twilio account or to change the phone number in the test/call.js file line 122.

**Comment by striderkiin** [comment]
I have a similar issue and I've updated the test/call.js file line 22 @Ross1337

**Comment by Ross1337** [comment]
Check what's the twillio error by running the api and making a test call on the localhost:1337/call route using insomnia, it'll show you the error that twilio is responding

**Comment by haxfud** [comment]
Bro Your error Fixed Same Issue With Me Help Please

**Comment by Falun2002** [comment]
My phone does not ring, the calls in twilio do not show

**Comment by haxfud** [comment]
Falun2002 ( you getting any other error

**Comment by Ross1337** [comment]
> My phone does not ring, the calls in twilio do not show

So your config.js file is badly configured

**Comment by Falun2002** [comment]
And where to find for the USA

**Comment by Falun2002** [comment]
Paypal Voice

**Comment by Ross1337** [comment]
You need it to make it yourself
