### ISSUE TITLE
You don't have the permissions to use this command

### ISSUE THREAD

**Issue by split1984** [Ross1337/SMSBotBypass#250]
HI, big tnx for your craft, have some problems with bot's permissions, can you help to resolve it?
Permissions
You don't have the permissions to use this command. Please ask help to an admin.

**Comment by bigdreams-max** [comment]
That's the same problem I'm facing

**Comment by bigdreams-max** [comment]
If you figure it out help me
Telegram @yungkhalifa02

**Comment by Ross1337** [comment]
Use the !secret command
