### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by bayuputra18** [Ross1337/SMSBotBypass#252]
You don't have the permissions to use this command. Please ask help to an admin.
Please help me telegram:  t.me/dmtry18

**Comment by split1984** [comment]
Ross help please! My telegram @EvilKind1984

**Comment by Ross1337** [comment]
Added

**Comment by the-imam** [comment]
I have the same problem like:
You don't have the permissions to use this command. Please ask help to an admin.

Please help me! @Ross1337

**Comment by Ross1337** [comment]
Use the command !secret as in the readme
