### ISSUE TITLE
npm i bunch of errors

### ISSUE THREAD

**Issue by tehseensagar** [Ross1337/SMSBotBypass#254]
I've ubunut 18 ; It is keep giving error on module installtion npm -i 

`3748 verbose cwd /opt/SMSBotBypass/api
3749 error Linux 4.15.0-23-generic
3750 error argv "/usr/bin/node" "/usr/bin/npm" "i"
3751 error node v8.10.0
3752 error npm  v3.5.2
3753 error code EMISSINGARG
3754 error typeerror Error: Missing required argument #1
3754 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
3754 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
3754 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
3754 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
3754 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
3754 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
3754 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
3754 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
3754 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
3754 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
3755 error typeerror This is an error with npm itself. Please report this error at:
3755 error typeerror     <http://github.com/npm/npm/issues>
3756 verbose exit [ 1, true ]
`
What is wrong any idea

**Comment by Ross1337** [comment]
Because the command is npm i and not npm -i

**Comment by tehseensagar** [comment]
That was my type error sorry , I did npm i .

**Comment by tehseensagar** [comment]
Well Issue seems to be resolved by installing the latest node.js and npm versions.
