### ISSUE TITLE
Nothing happen

### ISSUE THREAD

**Issue by crocodeal45** [Ross1337/SMSBotBypass#257]
HI
First, thanks for your work 
I followed all the instructions to install. Everything is ok but at the end when I run the command !call tel defaut i got a message : 

The api call has been sent to "tel  number " using default service. and nothing else. 
Can you help me, i read the others issues to check someone like me but i dont find

Tried to open 1337 but nothing change 

Thanks a lot

**Comment by crocodeal45** [comment]
Please add me on my telegram : @Ecotimes13

**Comment by Ross1337** [comment]
Hello, added
