### ISSUE TITLE
SmsBotBypass

### ISSUE THREAD

**Issue by tengri23** [Ross1337/SMSBotBypass#26]
Hi Bro

thank you very much for your sharing, I want to consult you about something. I will be glad if you send me an e-mail

skywolf@tuta.io

Thank you

**Comment by Ross1337** [comment]
Hello, consult me there.

**Comment by tengri23** [comment]
First of all, I would like to ask for your help in the installation of the program for the health program. I really need this program.

Thanx

ProtonMail mobil ile gönderildi

-------- Özgün İleti --------
17 Ağu 2021 13:26, Ross yazdı:

**Comment by Ross1337** [comment]
I don't help people with the installation of the bot. Why would I help you ?

**Comment by tengri23** [comment]
You're right, I can pay for helping with my first win

ProtonMail mobil ile gönderildi

-------- Özgün İleti --------
17 Ağu 2021 14:26, Ross yazdı:

**Comment by Ross1337** [comment]
Check your mails.

**Comment by bigbuddy82** [comment]
Hi Ross, First of all thanks and appreciation for this great work. I have some doubts and needs. Can you please kindly ping me in this discord id: biggbuddy#5454 waiting for your messages. Thanks in advance
