### ISSUE TITLE
Uncaught AssertionError: expected { Object (error) } to not have property 'error (Ros please Help me)

### ISSUE THREAD

**Issue by derainbow** [Ross1337/SMSBotBypass#264]
i got an error " Uncaught AssertionError: expected { Object (error) } to not have property 'error' at /root/SMSBotBypass/api/test/call.js:129:46
what does mean ?

ros please help me mytele: sdjangkero

**Comment by Ross1337** [comment]
Added

**Comment by jcoutts69** [comment]
what was the fix for it im getting the same error @derainbow

**Comment by jcoutts69** [comment]
add my tele @Ross1337 jcoutts45

**Comment by sofien00000** [comment]
my tele sofien000 please send me the solution and thanks!

**Comment by Ross1337** [comment]
Added
