### ISSUE TITLE
HOW DO I INSTALL DEPENDENCIES 

### ISSUE THREAD

**Issue by TyDrizzle** [Ross1337/SMSBotBypass#27]
I just need to figure out how to install the dependencies that’s it if you can show me message me on discord TyDrizzle#3156

**Comment by Ross1337** [comment]
Check your discord.

**Comment by JARVIS-124** [comment]
> Check your discord.

Can you share a video file on setting up all things in my discord or help me in TeamViewer please my discord.  ! ` J∆RVIS™#0569

**Comment by Ross1337** [comment]
Your discord isn't working.

**Comment by Recklessmama786** [comment]
Hey I'm also needing help figuring out how to add the dependencies. My discord is Lillypete#1481

**Comment by zangueblo** [comment]
Please can you help me with everything I need to install everything? I can't
my telegram @bankz1
my discord blood#9407

**Comment by Ross1337** [comment]
Done

**Comment by zangueblo** [comment]
> Terminé

le s je n'ai pas capté t'a dis quoi ?

moi je partient pas à tout faire

**Comment by Ross1337** [comment]
Hello, whats your problem ?
