### ISSUE TITLE
Cant initiate calls

### ISSUE THREAD

**Issue by arorrev** [Ross1337/SMSBotBypass#274]
Can you please help my telegram @Arorrev

**Comment by arorrev** [comment]
https://prnt.sc/24tx6ks
New issue

**Comment by arorrev** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/96744034/147497722-4e09e0ca-b8f6-4468-818e-2f0f0a6681da.png)

**Comment by arorrev** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/96744034/147497751-3eda2d1f-4263-4280-a6a8-590e69a8ee71.png)
Not sending calls

**Comment by arorrev** [comment]
Help me with this please

**Comment by Ross1337** [comment]
Added on telegram
