### ISSUE TITLE
 API Url & Api Password

### ISSUE THREAD

**Issue by bvm7x** [Ross1337/SMSBotBypass#278]
Sir Thank you for this wonderful work, Have some problems in installation you ca help me.

problem:
node bot.js

    reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { error: 'Invalid password.' }
--------------------------------------------------------------------
When I tried his reform gives me this error
-----------------------------------------------------------------------
 },
    _currentUrl: 'http://127.0.0.1:1337/call/',
    [Symbol(kCapture)]: false
-------------------------------------------------------------------------

**Comment by arorrev** [comment]
your api pass that you have in the config file in the api folder should be the same as in the bot.js file

check it again it might be different thats why there is an invalid password error

**Comment by Ross1337** [comment]
Hello, give me your telegram

**Comment by jhonpower94** [comment]
please contact me on telegram i need support connecting the discord bot

**Comment by jhonpower94** [comment]
telehram @jhonpower

**Comment by Ross1337** [comment]
Done
