### ISSUE TITLE
translated script but have problem

### ISSUE THREAD

**Issue by Venmosa** [Ross1337/SMSBotBypass#286]
i translated the script to english and included it in the code but when it calls me it says Bonjour and then the english script plays
how do you remove the bonjour part.
please help <3

**Comment by Ross1337** [comment]
File voice.js

**Comment by koehlerd33** [comment]
@Venmosa did you figure it out how to change bonjour? I've removed in voice.js but still says bonjour....

**Comment by Ross1337** [comment]
Have you reboot your api ?
