### ISSUE TITLE
problem adding new call services

### ISSUE THREAD

**Issue by Venmosa** [Ross1337/SMSBotBypass#287]
i have added a new module called foodora and i made a language script and i included the path of it in the config.js file 
and when i try to call that module it wont call my number idk why this is happening help would be nice <3

**Comment by giotihaxx** [comment]
can you give me please 


my problem
 Call.js
    /call POST
      √ it should return an ERROR with "Please post all the informations needed." : we sent no post data
      √ it should return an ERROR with "Please post all the informations needed." : we sent 1 post data
      √ it should return an ERROR with "Please post all the informations needed." : we sent 2 post data
      √ it should return an ERROR with "The service wasn't recognised." : we sent 3 post data (but bad service)
      √ it should return an ERROR with "Bad phone number." : we sent 3 post data (but bad phone number)
      1) it should return the callSid : everything's fine

**Comment by giotihaxx** [comment]
Call.js
       /call POST
         it should return the callSid : everything's fine:
     Uncaught AssertionError: expected { Object (error) } to not have property 'error'
      at C:\Users\Max\Desktop\SMSBotBypass-master\api\test\call.js:129:46
      at Test.Request.callback (node_modules\superagent\lib\node\index.js:716:12)
      at C:\Users\Max\Desktop\SMSBotBypass-master\api\node_modules\superagent\lib\node\index.js:916:18
      at IncomingMessage.<anonymous> (node_modules\superagent\lib\node\parsers\json.js:19:7)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Ross1337** [comment]
Venmose your modifications have been badly done
