### ISSUE TITLE
adding bot to server

### ISSUE THREAD

**Issue by d0p3r0b0t** [Ross1337/SMSBotBypass#29]
So im brand new to discord and im assuming a lot was left out assuming people were familiar...I am at the part after creatig roles to add bot to server. I seem to have gone down a rabbit hole reading documentation exactly how to do that, telling me to add application in order to add bot...this sucks i cant really even word my question right..
so im stuck at the oauth2 gen. do i mess with adding redirects and all that or .....damn i feel like a tool...can you or someone wiser write me a short to the point, slightly more detailed step by step?
Ill spark a fat spliff with ya mayne if someone could help me.. shit ill teamview with someone if ya want

**Comment by d0p3r0b0t** [comment]
well holy chit...i finally got it to spit out a url and hae authorized it....assuming i am headed the correct direction?

**Comment by d0p3r0b0t** [comment]
well i ran node bot.js without errors so i guessing thats good

**Comment by d0p3r0b0t** [comment]
sorry guys...guess i needed to say it out loud lol...its working now..well, i gotta give myself permission apparently but im stoked

**Comment by Ross1337** [comment]
Everything has been solved ?
