### ISSUE TITLE
does anybody know a fix?

### ISSUE THREAD

**Issue by cstreez** [Ross1337/SMSBotBypass#309]
![image](https://user-images.githubusercontent.com/96919648/147986259-4caecf36-9274-4457-8993-7842944878b9.png)

**Comment by JazySenpai** [comment]
Is your bot working fine ??

**Comment by cstreez** [comment]
Ig but I keep gettin this error

**Comment by Ross1337** [comment]
Yeah it works fine, is your twilio account upgraded ?

**Comment by Venmosa** [comment]
yo ross i have a problem. Everytime i change the line where it says bonjour in the start of each call like if i remove that shit i get this error in npm test and it fuck everything up 
![image](https://user-images.githubusercontent.com/96892570/148131585-1f12461b-b67d-4d6f-ae75-67ffb9ef061f.png)

**Comment by Venmosa** [comment]
ross you got a telegram?

**Comment by Ross1337** [comment]
Give me yours

**Comment by robapant** [comment]
![image](https://user-images.githubusercontent.com/96744703/149065276-9b4e4684-d56b-49a4-a5f7-df47c26c5874.png)

i get this exact does it mean i have to upgrade twillo

**Comment by robapant** [comment]
error*

**Comment by robapant** [comment]
all pass but that one

**Comment by robapant** [comment]
do i need to update the twillo acct

**Comment by michaelclelland83** [comment]
> do i need to update the twillo acct

account upgrade is to call any number, trial account is to call verified numbers.
