### ISSUE TITLE
opening the port

### ISSUE THREAD

**Issue by d0p3r0b0t** [Ross1337/SMSBotBypass#31]
I was using ngrok until i read a reply you saying it wasnt required?  anyone tried using noip?

eitherway imma upgrade twilio account first later today amd see how it goes

**Comment by Ross1337** [comment]
You can use it if you want but it's not required, it works with or without

**Comment by d0p3r0b0t** [comment]
hmmm, really?  So i just use my WAN IP and port 1337 for the server info in the config.js then?  cool thanks

gonna pay for upgraded twilio here in a minute and hopefully get it going today

**Comment by Ross1337** [comment]
Absolutly.
