### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by Kong10500** [Ross1337/SMSBotBypass#314]
hello bro @Ross1337 @ymophen 
please help me 
 [https://i.ibb.co/fCL0R8x/Untitled.png](url)

https://t.me/Man22643

**Comment by Kong10500** [comment]
![Untitled](https://user-images.githubusercontent.com/59892296/148237594-9c6c4167-d655-47cf-a98a-98aba7ff217f.png)

**Comment by Kong10500** [comment]
I don't really understand how to install it. can you help me for

**Comment by Ross1337** [comment]
Hello, added on tg

**Comment by Kong10500** [comment]
thanks
