### ISSUE TITLE
failing at test

### ISSUE THREAD

**Issue by juicypimp** [Ross1337/SMSBotBypass#317]
I have this error please someone help me  

1 failing

  1) Call.js
       /call POST
         it should return the callSid : everything's fine:
     Uncaught AssertionError: expected { Object (error) } to not have property 'error'

**Comment by juicypimp** [comment]
never mind. the test did run great. But when I make the api request through the discord bot, I don't receive the call on my cell phone... Could you please help me what is your tg

**Comment by juicypimp** [comment]
my telegram is @quantumpablo

**Comment by Ross1337** [comment]
Hello, added
