### ISSUE TITLE
all 27 Check pass, But Failed to connect error in Twilio

### ISSUE THREAD

**Issue by michaelclelland83** [Ross1337/SMSBotBypass#326]
Hi, while doing test, all 27 check passes. But same time in twilio i am getting error as shown below.
statusCallback
	"http://205.45.8.452:1337/status/ch45dsfdLVyhOtisXW8Gass6"
ErrorCode
	"11205"
LogLevel
	"WARNING"
Response
Headers
X-Twilio-WebhookError 11201 TCP connection timed out
X-Twilio-WebhookAttempt 2
X-Twilio-Reason HTTP connection failure
X-Twilio-WebhookRetriable true
Content-Length 472
Content-Type text/html
Body
Show Raw

Twilio was unable to fetch content from: http://205.45.8.452:1337/status/ch45dsfdLVyhOtisXW8Gass6
Error: Failed to connect to ip 20.121.4.153: connection timed out: /205.45.8.452:1337
Account SID: 4dad8a16c53vcddgf45fd55d
SID: ac1fc47f40ca3e3b95c343543fsdfsd6
Request ID: 80b2d341-1038-4faa-8f15-8a315fcd4faf
Remote Host: 205.45.8.452
Request Method: POST
Request URI: http://205.45.8.452:1337/status/ch45dsfdLVyhOtisXW8Gass6
URL Fragment: true

Please guide me in this. @Ross1337 , its my telegram ID, can you contact me on that please @Ryannerex

**Comment by michaelclelland83** [comment]
All Fixed, Working Now.

**Comment by incog5187** [comment]
Need otp bot asap

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 13, 2022 at 4:05 AM, ***@***.***> wrote:   


All Fixed, Working Now.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by michaelclelland83** [comment]
> Need otp bot asap Sent from Yahoo Mail on Android On Thu, Jan 13, 2022 at 4:05 AM, ***@***.***> wrote: All Fixed, Working Now. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Contact @Ryannerex at telegram

**Comment by LocalsGitHub** [comment]
im having this error, what is the solution?

**Comment by incog5187** [comment]
Don't no ill ask around for you 

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 7, 2022 at 1:58 PM, ***@***.***> wrote:   


im having this error, what is the solution?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ross1337** [comment]
You need to open your port

**Comment by LocalsGitHub** [comment]
> You need to open your port

I already have the port open (sudo ufw allow 1337) I also opened HTTP and HTTPS ports. (sudo ufw allow HTTP) and (sudo ufw allow HTTPS)

I also allowed the HTTP and HTTPS ports open and port 1337 on the digital ocean networking page.
![image](https://user-images.githubusercontent.com/76016636/153032751-4271818a-7263-4074-98de-329335affec5.png)

**Comment by Ross1337** [comment]
If it does not work use ngrok instead

**Comment by incog5187** [comment]
Can you help me out..I'm btc ready 

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 10, 2022 at 12:40 PM, ***@***.***> wrote:   


If it does not work use ngrok instead

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
