### ISSUE TITLE
Need Urgent Help 24 Passing 3 Failing

### ISSUE THREAD

**Issue by thefakedwc** [Ross1337/SMSBotBypass#327]
> SMS-Bypass@1.0.0 test
> mocha --timeout 10000

  App.js
    test the APP routes
      ✓ test /voice/ : we are looking for a 200 status
Setup the new api password : done.
Automatic setup : done.
      ✓ test /get/ : we are looking for a 200 status
      ✓ test /sms/ : we are looking for a 200 status (788ms)
      ✓ test /status/ : we are looking for a 200 status
      ✓ test /stream/default : we are looking for a 200 status
      ✓ test /call/ : we are looking for a 200 status

  Authentification.js
    /get POST to check authentification.js middleware
      ✓ it should return "Please send the password API." : we are not sending any password post
      ✓ it should return "The password you sent is empty." : we are not sending an empty password
      ✓ it should return "Invalid password." : we are sending a bad password
      ✓ it should return be good : no error

  Call.js
    /call POST
      ✓ it should return an ERROR with "Please post all the informations needed." : we sent no post data
      ✓ it should return an ERROR with "Please post all the informations needed." : we sent 1 post data
      ✓ it should return an ERROR with "Please post all the informations needed." : we sent 2 post data
      ✓ it should return an ERROR with "The service wasn't recognised." : we sent 3 post data (but bad service)
      ✓ it should return an ERROR with "Bad phone number." : we sent 3 post data (but bad phone number)
      1) it should return the callSid : everything's fine

  Config.js
    twilio INFORMATIONS
      ✓ checking the twilio logins using the api : should allow to use it
    api INFORMATIONS
      2) check the api password
    services FILEPATH
      3) check the services FILEPATH and if the files exists

  Get.js
    /get POST
      ✓ it should return "Invalid callSid." : we are not sending any callSid
      ✓ it should return "Invalid callSid." : we are sending a bad callSid
      ✓ it should return the call info's : we are sending a good callSid

  Voice.js
    /voice POST
      ✓ it should return an ERROR "Please give us the callSid." : we are not sending any callSid
      ✓ it should return the twiML code for the paypal service : we are not sending any callSid or digit
      ✓ it should return the twiML code for the default service : the service is not precised in the db
      ✓ it should return the twiML code for the default service : the service asked doesn't exist
      ✓ it should return the twiML code for the end service : we provided the 6 digits code

  24 passing (1s)
  3 failing

  1) Call.js
       /call POST
         it should return the callSid : everything's fine:
     Uncaught AssertionError: expected { error: 'Bad phone number.' } to not have property 'error'
      at /Users/haks/Downloads/GIFPaper-master/SMSBotBypass-master/api/test/call.js:129:46
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:716:12)
      at /Users/haks/Downloads/GIFPaper-master/SMSBotBypass-master/api/node_modules/superagent/lib/node/index.js:916:18
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/parsers/json.js:19:7)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

  2) Config.js
       api INFORMATIONS
         check the api password:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/config.js:36:27)
      at processImmediate (node:internal/timers:473:21)

  3) Config.js
       services FILEPATH
         check the services FILEPATH and if the files exists:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true
      
      at /Users/haks/Downloads/GIFPaper-master/SMSBotBypass-master/api/test/config.js:45:62
      at Array.forEach (<anonymous>)
      at Context.<anonymous> (test/config.js:44:22)
      at processImmediate (node:internal/timers:473:21)

**Comment by michaelclelland83** [comment]
1st error is not an issue. other  2 are issue in config file
