### ISSUE TITLE
BOT IS NOT CALLING

### ISSUE THREAD

**Issue by jitflow2134** [Ross1337/SMSBotBypass#329]

**Comment by incog5187** [comment]
Ever get bot to work 

Sent from Yahoo Mail on Android 
 
  On Wed, Jan 12, 2022 at 6:54 PM, ***@***.***> wrote:   


Closed #329.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
