### ISSUE TITLE
502 Gateway

### ISSUE THREAD

**Issue by jitflow2134** [Ross1337/SMSBotBypass#333]
when i run npm test this show up. i tried changes api password thinking that would help but it didnt 
please help  @Ross1337 

![2022-01-12 (3)](https://user-images.githubusercontent.com/93065996/149249756-906c9c07-5d8c-4e36-ab92-d084b59e7ae7.png)

**Comment by Ross1337** [comment]
Hello, give me your telegram

**Comment by jitflow2134** [comment]
> Hello, give me your telegram

my tele is @lisesavv

**Comment by Ross1337** [comment]
Added
