### ISSUE TITLE
 SMSBotBypass

### ISSUE THREAD

**Issue by yfinality** [Ross1337/SMSBotBypass#341]
Hello.
Please just write where and how ??? Support this beautiful project.
I am waiting for a reply along with guidelines.

**Comment by Ross1337** [comment]
Hello, what do you mean ?

**Comment by Ross1337** [comment]
If you wanna contact me, check my tg on my bio

**Comment by Ross1337** [comment]
Give me your tg

**Comment by Ross1337** [comment]
Added
