### ISSUE TITLE
Sorry, an application error has occured goodbye!

### ISSUE THREAD

**Issue by david09baz** [Ross1337/SMSBotBypass#344]
I have upgraded my twilio account, used ngrok to forward 1337 to localhost.
When i do !call NUMBER SERVICE, it calls me but there is an automated voice that says Sorry, an application error has occured goodbye! I also dont know what my api url is and i would like help to set it up. @Ross1337 

My discord is: TriplVibe 0155
My telegram is @hakalmnop

**Comment by Ross1337** [comment]
Hello, added on tg
