### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by Errupti0n** [Ross1337/SMSBotBypass#350]
I am trying to fix this issue for real while 

![image](https://user-images.githubusercontent.com/92153256/149890274-dcbdfc6b-da26-4b2d-9580-5e0bd23fc8f5.png)

I can't see to fix this I also have opened the port 1337 from firewall 

I have this much balance in twilio 
![image](https://user-images.githubusercontent.com/92153256/149890437-b105ba2e-6079-4e4f-8952-29ec6ead040a.png)
Trying to fix this for long time please anyone help much appreciated

Also running API and bot at the same time in different command prompts

Telegram: @C00kie143
Discord: DarkShadow#8676

**Comment by Medox03** [comment]
same for me :'(

**Comment by Ross1337** [comment]
> 

Give me your telegram

**Comment by Errupti0n** [comment]
> > 
> 
> Give me your telegram

Here @C00kie143

**Comment by Ross1337** [comment]
Added
