### ISSUE TITLE
API Url & Api Password

### ISSUE THREAD

**Issue by amongushjk** [Ross1337/SMSBotBypass#358]
where do i get the API Url & Api Password

**Comment by CoreLine76** [comment]
[www.twilio.com](https://www.twilio.com/)

**Comment by amongushjk** [comment]
in which page i can find them i only see token and sid

**Comment by CoreLine76** [comment]
[https://www.hizliresim.com/gl4xziq](url)

If you can't, post your telegram here.

**Comment by amongushjk** [comment]
dm me bro @D4UFOO

**Comment by CoreLine76** [comment]
ok
