### ISSUE TITLE
Error throw after making call from discord

### ISSUE THREAD

**Issue by gtoolsAdmin** [Ross1337/SMSBotBypass#367]
Express server started on *:1337
C:\wamp64\www\SMSBotBypass\api\node_modules\discord-webhook-node\src\classes\webhook.js:74
            if (this.throwErrors) throw new Error(err.message);
                                        ^

Error: Only absolute URLs are supported
    at Webhook.send (C:\wamp64\www\SMSBotBypass\api\node_modules\discord-webhook-node\src\classes\webhook.js:74:41)

**Comment by Ross1337** [comment]
Hello, bad configuration
