### ISSUE TITLE
Help me to set this up.

### ISSUE THREAD

**Issue by MosaabDevv** [Ross1337/SMSBotBypass#369]
Can some1 help me to set this up ?

Paying in Paypal / Crypto

Discord = Mosaab#7777
Telegram = MeneerA.
Cracked.io = bart071x

**Comment by Ross1337** [comment]
Hello, telegram not working

**Comment by 666Siri** [comment]
May I get help also It would be greatly appreciated
Telegram @siri10k

**Comment by sbilyamin** [comment]
Can u pls help me telegram 
@Tshelby001

**Comment by sbilyamin** [comment]
![Screenshot_20220204-165054_Telegram.jpg](https://user-images.githubusercontent.com/98608813/152559608-ccd116e9-331b-4376-9470-682f5ebded5c.jpg)

**Comment by sbilyamin** [comment]
I sent u message but it's not going, pls help sir
Telegram (Tshelby001)

**Comment by Ross1337** [comment]
Added

**Comment by Monte1288** [comment]
Ross bro please check DM and reply me please

**Comment by Monte1288** [comment]
![16439946443898790545852346953255](https://user-images.githubusercontent.com/98557398/152572446-0008862a-b9cf-4b3e-97d5-3a627842f7c6.jpg)

But call not sending

**Comment by Ross1337** [comment]
Check the /call/ request response

**Comment by Monte1288** [comment]
How to use any spoof caller id with twilio??
