### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Ilivein404** [Ross1337/SMSBotBypass#371]
When i go to localhost to view site (http://127.0.0.1:1337/)
Im keep getting

{"error":"Not found, or bad request method."}

![image](https://user-images.githubusercontent.com/99034277/152556653-4a4cc4cb-efe7-4cd9-b374-92ac3e817320.png)

![image](https://user-images.githubusercontent.com/99034277/152556743-d4ef3db4-7b7f-43c6-8d4c-b4608e6c51cc.png)

![image](https://user-images.githubusercontent.com/99034277/152556819-c71f049b-ef28-4c0d-94b9-c5b79a1fbb16.png)

**Comment by Ilivein404** [comment]
I thought i have to go here to view calls? Because every time i try to call it doesn't send a call.
Are we able to talk on discord for some more help? if so my discord is Luckyu#5112

**Comment by BlueSkySt** [comment]
> I thought i have to go here to view calls? Because every time i try to call it doesn't send a call. Are we able to talk on discord for some more help? if so my discord is Luckyu#5112

have u tried the 'npm test' ?

**Comment by Ilivein404** [comment]
> 

I see that i am getting this 
![image](https://user-images.githubusercontent.com/99034277/152569689-b9cdcfae-d65b-4f6d-91d6-27323a75e343.png)
Any fixes?

**Comment by Ilivein404** [comment]
![image](https://user-images.githubusercontent.com/99034277/152573189-b68ca98c-d4cb-4f34-9fc0-5e4f09e30f9e.png)
@Ross1337 I believe it is because the caller id is not put in the way it needs to be? could you send the format it needs sent in?

![image](https://user-images.githubusercontent.com/99034277/152573418-25aa3326-d4f9-49ae-8125-3bb165b4ea00.png)

**Comment by Monte1288** [comment]
How to use any unverified caller id??

**Comment by Ilivein404** [comment]
> 

Mines a verifyed ID
