### ISSUE TITLE
Error when trying to call

### ISSUE THREAD

**Issue by Gittyhup** [Ross1337/SMSBotBypass#38]
I be getin this error constantly how fix  

data: { error: 'Invalid password.' }

**Comment by Ross1337** [comment]
Wrong discord id, can you send a working one ?

**Comment by Gittyhup** [comment]
amcool#0666 My bad.

**Comment by elva222** [comment]
amcool#0666. I Sent you a request. Check it

**Comment by Zeph-ChasesBags** [comment]
i have the same problem my discord name is : 𝐙𝐄𝐏𝐇#0001

and yes my name has that font so copy and paste my username
