### ISSUE TITLE
We're sorry. An application error has occured.

### ISSUE THREAD

**Issue by belmeg** [Ross1337/SMSBotBypass#4]
When I call my self, this is what I get by doing "!call NUMBER paypal" any idea why ?

**Comment by bbeltran1** [comment]
I do all steps in npm test every thing work perfect but in discord give admin permision error and I dont understand because I create like role administrator

**Comment by bbeltran1** [comment]
When I put !call number any service give admin permision error in discord

**Comment by Ross1337** [comment]
Hello guys, sorry for the inactivity ! The problem is not from the bypass api but from the discord bot. Have you done the !secret yoursecretpassword @user ? It's used to get the permissions. For belmeg, I think you didn't configured the discord bot well

**Comment by BigBlackDz-wq** [comment]
bro when i start node bot.js and make !call the phone number paypal for exampl the bot.js stops and don't make the call  so can you help me

**Comment by Ross1337** [comment]
Is the npm test working ?

**Comment by BigBlackDz-wq** [comment]
Yes

**Comment by BigBlackDz-wq** [comment]
Send me discord or your email i want to contact you directly if y want

**Comment by bbeltran1** [comment]
I want to contact you too

**Comment by bbeltran1** [comment]
Npm test working perfect but I want to ask you my twilio account is trial maybe that would be the problem for sms receiving because in twilio log show me error

**Comment by bbeltran1** [comment]
But in discord bot show me sent perfectly

**Comment by Ross1337** [comment]
Ok this is your twilio account, you need to upgrade it, my discord account has been banned sorry boys

**Comment by allseyer** [comment]
1) it should return the callSid : everything's fine

 1 failing

Call.js
       /call POST
         it should return the callSid : everything's fine:
     Uncaught AssertionError: expected { Object (error) } to not have property 'error'  


npm ERR! code 1
npm ERR! path /home/nisamm/SMSBotBypass/api
npm ERR! command failed
npm ERR! command sh -c mocha --timeout 10000

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/leo/.npm/_logs/2021-04-02T08_47_59_655Z-debug.log


how can i fix those errors ?? 
pleas help

**Comment by Ross1337** [comment]
Is your twilio account upgraded ?

**Comment by allseyer** [comment]
Sadly my twilio acc isn't updated 

Should the update fix everything?

**Comment by Ross1337** [comment]
Yup upgrade your twilio account and it should solve the problem
