### ISSUE TITLE
explain

### ISSUE THREAD

**Issue by Dmlee142** [Ross1337/SMSBotBypass#40]
var numdigits = service == 'coinbase' ? '9' : '6'; here what is the extra 6 doing here ui m not able to indicate sperate otp lenght like some i have done 5 rest are not being set help me with correct code

**Comment by Dmlee142** [comment]
ross kindly write a code like we tell each service name and then otp length in discord write me a code kindly

**Comment by Ross1337** [comment]
What are you talking about ?

**Comment by Dmlee142** [comment]
I want to set custom otp length for custom service

Like for coinbase I want user to input 7 Digit

**Comment by Dmlee142** [comment]
?

**Comment by Dmlee142** [comment]
Would u like to reply bro

**Comment by Ross1337** [comment]
What do you wanna know ?

**Comment by Dmlee142** [comment]
I want to set custom input like I want user to input 7 digit on keypad for specific service

**Comment by Dmlee142** [comment]
Will you reply ?

**Comment by Ross1337** [comment]
I have a life beyond your needs, if you wanna custom this code, ask a developper or pay me.
