### ISSUE TITLE
stucks  on express server started on : insert port 

### ISSUE THREAD

**Issue by IchiyouRuri** [Ross1337/SMSBotBypass#41]
yo mind helping me it stucks on here 
![image](https://user-images.githubusercontent.com/86968583/131212407-08aceb05-0b27-4190-9462-55bac91f0145.png)
my discord is Ruripapi#0965

**Comment by Dmlee142** [comment]
It's not wrong

**Comment by IchiyouRuri** [comment]
> It's not wrong

the bot wont start tho

**Comment by Dmlee142** [comment]
Lmao don't use it his is old and will not work for bypass just stop using

**Comment by Ross1337** [comment]
Lol, if you don't read the readme and follow all the instructions you cannot make work the bot. It's like if you are making legos without following the instructions.

**Comment by IchiyouRuri** [comment]
> Lol, if you don't read the readme and follow all the instructions you cannot make work the bot. It's like if you are making legos without following the instructions.

just reliazed after 5 hours lmfao
