### ISSUE TITLE
Custom numdigit length

### ISSUE THREAD

**Issue by Dmlee142** [Ross1337/SMSBotBypass#43]
I want to set custom input like I want user to input 7 digit on keypad for specific service

I am not able to add custom num digits for specific service. Example I need user to press 7 digit for banque service

**Comment by Ross1337** [comment]
Understand the code and modify it.

**Comment by Dmlee142** [comment]
I tried man please don't make it difficult I am not able to that's why I am here to ask

**Comment by Dmlee142** [comment]
Ok will pay u msg me @cyberbabu telegram and I wl tell you scheme

**Comment by Dmlee142** [comment]
When replying bruh
