### ISSUE TITLE
Stuck on Go to our API folder lol

### ISSUE THREAD

**Issue by k2-cell** [Ross1337/SMSBotBypass#46]
Well i thought i knew what i was doing given the previous experince of using kali, sadly when i type the command (and copy and paste) it says "no such file or directory: /SMSBotBypass/api/ "

**Comment by k2-cell** [comment]
please right to me on discord kilo#7836

**Comment by k2-cell** [comment]
nevermind fixed issue, you did not need to add the "/" after cd for my verssion of kali......

**Comment by F16shooter** [comment]
can you help me

**Comment by F16shooter** [comment]
i have the same problem

**Comment by Ross1337** [comment]
Just use cd /SMSBotBypass/api
