### ISSUE TITLE
Twilio

### ISSUE THREAD

**Issue by Psvbenn** [Ross1337/SMSBotBypass#5]
Twilio blocked the call setup. What are the alternatives?

**Comment by Ross1337** [comment]
What do u mean ? I didn't understood

**Comment by Psvbenn** [comment]
I did set up the SMSBotbypass on Linux, discord and twilio perfectly but it seems twilio blocked the calls from going through. The Bot is working perfectly but the calls is always blocked by twilio. Have you had similar experience?

**Comment by Ross1337** [comment]
Is your twilio account upgraded ?

**Comment by Psvbenn** [comment]
Yes, I paid $20 into my twilio account and it was upgraded. Please send me your email address so that I can send you the messages I received from Twilio. My email address is psvbenn@gmail.com
I need you to guide me through the setup please

**Comment by Psvbenn** [comment]
This is one of Twilio's message
Special Advisory About Your Twilio Compliance Obligations Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio  Was this helpful?Yes \| NoThis email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.Twilio Notifications375 Beale Street, Suite 300 , San Francisco, CA 94105Unsubscribe | Special Advisory About Your Twilio Compliance Obligations Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio  Was this helpful?Yes \| NoThis email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.Twilio Notifications375 Beale Street, Suite 300 , San Francisco, CA 94105Unsubscribe | Special Advisory About Your Twilio Compliance Obligations Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio  Was this helpful?Yes \| NoThis email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.Twilio Notifications375 Beale Street, Suite 300 , San Francisco, CA 94105Unsubscribe | Special Advisory About Your Twilio Compliance Obligations Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio  Was this helpful?Yes \| NoThis email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.Twilio Notifications375 Beale Street, Suite 300 , San Francisco, CA 94105Unsubscribe |   |   | Special Advisory About Your Twilio Compliance Obligations | Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio | Was this helpful?Yes \| No | This email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Special Advisory About Your Twilio Compliance Obligations Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio  Was this helpful?Yes \| NoThis email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.Twilio Notifications375 Beale Street, Suite 300 , San Francisco, CA 94105Unsubscribe | Special Advisory About Your Twilio Compliance Obligations Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio  Was this helpful?Yes \| NoThis email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.Twilio Notifications375 Beale Street, Suite 300 , San Francisco, CA 94105Unsubscribe | Special Advisory About Your Twilio Compliance Obligations Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio  Was this helpful?Yes \| NoThis email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.Twilio Notifications375 Beale Street, Suite 300 , San Francisco, CA 94105Unsubscribe |   |   | Special Advisory About Your Twilio Compliance Obligations | Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio | Was this helpful?Yes \| No | This email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.
Special Advisory About Your Twilio Compliance Obligations Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio  Was this helpful?Yes \| NoThis email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.Twilio Notifications375 Beale Street, Suite 300 , San Francisco, CA 94105Unsubscribe | Special Advisory About Your Twilio Compliance Obligations Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio  Was this helpful?Yes \| NoThis email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.Twilio Notifications375 Beale Street, Suite 300 , San Francisco, CA 94105Unsubscribe |   |   | Special Advisory About Your Twilio Compliance Obligations | Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio | Was this helpful?Yes \| No | This email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.
Special Advisory About Your Twilio Compliance Obligations Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio  Was this helpful?Yes \| NoThis email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.Twilio Notifications375 Beale Street, Suite 300 , San Francisco, CA 94105Unsubscribe |   |   | Special Advisory About Your Twilio Compliance Obligations | Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio | Was this helpful?Yes \| No | This email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.
 
 
Special Advisory About Your Twilio Compliance Obligations
Ahoy! As part of Twilio’s on-going effort to help you build safe and trusted communications with your customers, we wanted to remind all of our customers about the importance of adhering to Twilio’s Acceptable Use Policy and Messaging Policy.  If you are an Independent Software Vendor (ISV) - a Twilio customer who uses Twilio services in the delivery of your services to your own clients (see End Users as defined in our Terms of Service) - that means your responsibility to adhere to our policies extends to the activity of your customers.   It is especially important for ISVs to have systems in place to continuously monitor their customers’ activities to detect, isolate and immediately remediate illegal activity and unwanted communications on their Twilio account.  If we identify a violation of our terms or policies, we will work with you in good faith to get you back into compliance when situations allow. However, in certain cases, such as illegal or criminal activity, we will take immediate action to limit or suspend your access to the Twilio platform. Thank you for doing your part in building safe and trusted communications, and if you’re an ISV, thank you also for educating your customers on acceptable use and holding them accountable to our policies. Sincerely,  Team Twilio
Was this helpful?Yes \| No
This email was sent to you in regard to an associated Twilio account or business relationship.If you have any questions or concerns, please go to https://support.twilio.com to reach our Support team.

**Comment by Psvbenn** [comment]
Do you think it is Twilio that blocked my account because my Bot is working perfectly but an error is returned on Linux that the calls made by my Bot is not going through. Please help me

**Comment by Ross1337** [comment]
Is your server port open ?

**Comment by Ross1337** [comment]
Reopen this I can't reopen it lol

**Comment by Psvbenn** [comment]
@Ross1337 This was the complications I faced when I tried to do the full setup in April. Can you assist me with the full setup pls?

**Comment by Psvbenn** [comment]
Can I reopen this issue?

**Comment by Ross1337** [comment]
Yeah
