### ISSUE TITLE
Error when running npm test

### ISSUE THREAD

**Issue by UnoHvH** [Ross1337/SMSBotBypass#50]
1) Config.js
       api INFORMATIONS
         check the api password:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\config.js:36:27)
      at processImmediate (internal/timers.js:464:21)

npm ERR! Test failed.  See above for more details.

**Comment by UnoHvH** [comment]
my api password is set fine

**Comment by UnoHvH** [comment]
i also get this when i run the server

> node api

Express server started on *:1337   ( is that a problem)

**Comment by UnoHvH** [comment]
ok i got the last issue fixed, but when i get the call is it meant to say a application error has occured or something else?

**Comment by Ross1337** [comment]
> i also get this when i run the server
> 
> > node api
> 
> Express server started on *:1337 ( is that a problem)

This is normal, what do you mean by "when i get the call" ? After doing the npm test ?
