### ISSUE TITLE
Discord Bot not sending calls

### ISSUE THREAD

**Issue by UnoHvH** [Ross1337/SMSBotBypass#51]
So i receive the test call but when i try to use the discord bot i just dont get a response no calls sent 

Error: connect ECONNREFUSED 124.168.133.204:1337
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '124.168.133.204',
  port: 1337,
  config: {
    url: 'http://124.168.133.204:1337/call/',
    method: 'post',
    data: 'password=ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789&to=971509797638&user=%40Uno%3F%231337&service=paypal&name=',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 103
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/call/',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '124.168.133.204',
      port: '1337',
      nativeProtocols: [Object],
      pathname: '/call/'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 103,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      socket: [Socket],
      _header: 'POST /call/ HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Content-Length: 103\r\n' +
        'Host: 124.168.133.204:1337\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/call/',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '124.168.133.204',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://124.168.133.204:1337/call/',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

**Comment by UnoHvH** [comment]
oh and just a disclaimer dont try to ddos that ip xD its already been changed since i made this post

**Comment by UnoHvH** [comment]
dunno if this is a problem Express server started on *:1337

**Comment by Ross1337** [comment]
No it isn't.

**Comment by Zeph-ChasesBags** [comment]
hey i have a problem with my api im getting so mutch errors.
i opened the port 1337 with ngrok and its working fine.
but idk what is the api password bc when i made the port on ngrok i didnt make a password so do i need a api password or what do i do bc im really confused please help

**Comment by Ross1337** [comment]
Port api = found in the config.js file ; it's an auto generated password for security.

**Comment by Zeph-ChasesBags** [comment]
App.js
    test the APP routes
      √ test /voice/ : we are looking for a 200 status
      √ test /get/ : we are looking for a 200 status
      √ test /sms/ : we are looking for a 200 status (1160ms)
      √ test /status/ : we are looking for a 200 status
      √ test /stream/default : we are looking for a 200 status
      √ test /call/ : we are looking for a 200 status

  Authentification.js
    /get POST to check authentification.js middleware
      √ it should return "Please send the password API." : we are not sending any password post
      √ it should return "The password you sent is empty." : we are not sending an empty password
      √ it should return "Invalid password." : we are sending a bad password
      √ it should return be good : no error

  Call.js
    /call POST
      √ it should return an ERROR with "Please post all the informations needed." : we sent no post data
      √ it should return an ERROR with "Please post all the informations needed." : we sent 1 post data
      √ it should return an ERROR with "Please post all the informations needed." : we sent 2 post data
      √ it should return an ERROR with "The service wasn't recognised." : we sent 3 post data (but bad service)
      √ it should return an ERROR with "Bad phone number." : we sent 3 post data (but bad phone number)
      1) it should return the callSid : everything's fine

  Config.js
    twilio INFORMATIONS
      √ checking the twilio logins using the api : should allow to use it
    api INFORMATIONS
      2) check the api password
    services FILEPATH
      √ check the services FILEPATH and if the files exists

  Get.js
    /get POST
      √ it should return "Invalid callSid." : we are not sending any callSid
      √ it should return "Invalid callSid." : we are sending a bad callSid
      √ it should return the call info's : we are sending a good callSid

  Voice.js
    /voice POST
      √ it should return an ERROR "Please give us the callSid." : we are not sending any callSid
      √ it should return the twiML code for the paypal service : we are not sending any callSid or digit
      √ it should return the twiML code for the default service : the service is not precised in the db
      √ it should return the twiML code for the default service : the service asked doesn't exist
      √ it should return the twiML code for the end service : we provided the 6 digits code


  25 passing (2s)
  2 failing

  1) Call.js
       /call POST
         it should return the callSid : everything's fine:
     Uncaught AssertionError: expected { Object (error) } to not have property 'error'
      at C:\Users\673Zeph\Desktop\SMSBotBypass-master\api\test\call.js:129:46
      at Test.Request.callback (node_modules\superagent\lib\node\index.js:716:12)
      at C:\Users\673Zeph\Desktop\SMSBotBypass-master\api\node_modules\superagent\lib\node\index.js:916:18
      at IncomingMessage.<anonymous> (node_modules\superagent\lib\node\parsers\json.js:19:7)
      at endReadableNT (internal/streams/readable.js:1317:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)

  2) Config.js
       api INFORMATIONS
         check the api password:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\config.js:36:27)
      at processImmediate (internal/timers.js:464:21)



npm ERR! Test failed.  See above for more details.

please help i set a random api password (matching with the bot api password) bc i dont know what im suppost to set the api password as.
when i

**Comment by Zeph-ChasesBags** [comment]
what im trying to ask is. what is the api password and where do i find one or make one.
is it releated to port forwarding or twilio.
im just confused and no one has answered my question yet so im asking

**Comment by Ross1337** [comment]
Api password = a random strong password generated to securise your api, if you want to make a call you need this password : this prevents others people to use your api. The api password is found in the config.js file. You can replace this password by anything you want exemple : Azerty123 or 123456789, but a strong and long password is recommended

**Comment by Zeph-ChasesBags** [comment]
App.js
    test the APP routes
      √ test /voice/ : we are looking for a 200 status
      √ test /get/ : we are looking for a 200 status
      √ test /sms/ : we are looking for a 200 status (799ms)
      √ test /status/ : we are looking for a 200 status
      √ test /stream/default : we are looking for a 200 status
      √ test /call/ : we are looking for a 200 status

  Authentification.js
    /get POST to check authentification.js middleware
      √ it should return "Please send the password API." : we are not sending any password post
      √ it should return "The password you sent is empty." : we are not sending an empty password
      √ it should return "Invalid password." : we are sending a bad password
      √ it should return be good : no error

  Call.js
    /call POST
      √ it should return an ERROR with "Please post all the informations needed." : we sent no post data
      √ it should return an ERROR with "Please post all the informations needed." : we sent 1 post data
      √ it should return an ERROR with "Please post all the informations needed." : we sent 2 post data
      √ it should return an ERROR with "The service wasn't recognised." : we sent 3 post data (but bad service)
      √ it should return an ERROR with "Bad phone number." : we sent 3 post data (but bad phone number)
      √ it should return the callSid : everything's fine (482ms)

  Config.js
    twilio INFORMATIONS
      √ checking the twilio logins using the api : should allow to use it
    api INFORMATIONS
      1) check the api password
    services FILEPATH
      √ check the services FILEPATH and if the files exists

  Get.js
    /get POST
      √ it should return "Invalid callSid." : we are not sending any callSid
      √ it should return "Invalid callSid." : we are sending a bad callSid
      √ it should return the call info's : we are sending a good callSid

  Voice.js
    /voice POST
      √ it should return an ERROR "Please give us the callSid." : we are not sending any callSid
      √ it should return the twiML code for the paypal service : we are not sending any callSid or digit
      √ it should return the twiML code for the default service : the service is not precised in the db
      √ it should return the twiML code for the default service : the service asked doesn't exist
      √ it should return the twiML code for the end service : we provided the 6 digits code


  26 passing (2s)
  1 failing

  1) Config.js
       api INFORMATIONS
         check the api password:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\config.js:36:27)
      at processImmediate (internal/timers.js:464:21)



npm ERR! Test failed.  See above for more details.


this is what i got after making a password in the config.js in the API and i made the same password in the bot config.js

**Comment by Ross1337** [comment]
Make a screenshot of your config.js file
