### ISSUE TITLE
Please help me with this

### ISSUE THREAD

**Issue by Zeph-ChasesBags** [Ross1337/SMSBotBypass#52]
i rant he npm test and i got a fully working api no errors
when i try to make a call with the bot it says ("The api call has been sent to 7278603735 using paypal service.")
7278603735 - is my text now number so i can see if it actually calls me.
when i send the command to call nothing calls my number what is the problem ??

**Comment by Ross1337** [comment]
You probably badly configured the config.js file for the discord bot, your discord bot is not sending the API Call

**Comment by Zeph-ChasesBags** [comment]
can i get your discord username so u can help me i cant send mine for some reason

**Comment by Ross1337** [comment]
Send me yours

**Comment by Zeph-ChasesBags** [comment]
here is my name i cant send it in github for somereason
https://pastebin.com/hs99mKyJ
so just go there and copy my name

**Comment by Zeph-ChasesBags** [comment]
UserFriendly#5042

**Comment by Zeph-ChasesBags** [comment]
did you add me yet?

**Comment by Ross1337** [comment]
Yes

**Comment by zangueblo** [comment]
Please can you help me with everything I need to install everything? I can't
my telegram @Bankz1
my discord blood#9407
