### ISSUE TITLE
API URL

### ISSUE THREAD

**Issue by g1us** [Ross1337/SMSBotBypass#53]
Hi. Could you please add me to discord and explain me what do you mean in the discord configuration by API URL? Or provide me the api url and where to insert my API Key details please. Thanks

Username: g1_us#1681

**Comment by d0p3r0b0t** [comment]
read the readme
all the questions you ask are answered

**Comment by Ross1337** [comment]
> read the readme
> all the questions you ask are answered

Thanks.
