### ISSUE TITLE
Sms call

### ISSUE THREAD

**Issue by Reweeee** [Ross1337/SMSBotBypass#54]
Hi. I did everything perfect, but when i call this message came and didnt receive any code 
![Screenshot_2](https://user-images.githubusercontent.com/90459558/132860034-69dd2b7b-f8f0-4596-9588-cde3a4b90a9e.png)
can you please help me

**Comment by Reweeee** [comment]
My discord is: Reweee | Kernelhost.ro#0005 if you can add me and help me.

**Comment by Reweeee** [comment]
My port giving me this error 
![image](https://user-images.githubusercontent.com/90459558/132900319-1867039b-c1ab-4ed5-9277-cb2919b7ca8d.png)

**Comment by d0p3r0b0t** [comment]
evryone seems stuck at this exact same spot...

**Comment by topboychoppa** [comment]
> My discord is: Reweee | Kernelhost.ro#1212 if you can add me and help me.

Please i need help with mine like i dont know how to start

**Comment by Ross1337** [comment]
If your discord bot is not sending the call, It's because you badly configured it with your api.

**Comment by Ross1337** [comment]
> My port giving me this error
> ![image](https://user-images.githubusercontent.com/90459558/132900319-1867039b-c1ab-4ed5-9277-cb2919b7ca8d.png)
dzaqd
Your using the wrong request method, you need to post on the page

**Comment by topboychoppa** [comment]
> If your discord bot is not sending the call, It's because you badly configured it with your api.

I know can you help me or walk me down the line please how can i contact you maybe on telegram or whatsapp

**Comment by Ross1337** [comment]
Give me your telegram

**Comment by topboychoppa** [comment]
@TopBoyChoppa

**Comment by topboychoppa** [comment]
TopBoyChoppa

**Comment by Skytechw** [comment]
@skytechw

> Give me your telegram

**Comment by Skytechw** [comment]
dm me plz

**Comment by Hope21x** [comment]
> Give me your telegram

I'm also in need of your help i did everything right but doesn't seem to be working for discord all though the api test is successful and working ..my telegram is @Tunchie_K .please help . thank you

**Comment by d0p3r0b0t** [comment]
yall post back here if yall figure it out...
im @digitaldopefiend on da tele

**Comment by Ross1337** [comment]
Problems are always the same for every people ... it's swelling

**Comment by Ross1337** [comment]
Always the same answer : configure well your discord config.js file
