### ISSUE TITLE
Please help me with this

### ISSUE THREAD

**Issue by Rasimx1** [Ross1337/SMSBotBypass#55]
![Екранна снимка (3)](https://user-images.githubusercontent.com/90567390/132994899-85e9433b-846f-4f3c-ba3a-b89a5cc4534d.png)

**Comment by Ross1337** [comment]
Hello, is your twilio account upgraded ?

**Comment by Rasimx1** [comment]
> Здравейте, вашият акаунт в twilio е надстроен?
Hi, Yes.
![Екранна снимка (4)](https://user-images.githubusercontent.com/90567390/132998757-a8415019-ef92-44a5-951b-d1d3ce029ed3.png)

**Comment by Ross1337** [comment]
What country do you try to call using twilio ?

**Comment by Rasimx1** [comment]
> В коя държава се опитвате да се обадите с помощта на twilio?

Unitited States (+1)
![Екранна снимка (5)](https://user-images.githubusercontent.com/90567390/133004939-a431c1f1-2506-4a80-bfea-f6c0d8897193.png)

**Comment by Ross1337** [comment]
![image](https://user-images.githubusercontent.com/45340378/133308300-f5f43127-c040-44f7-8942-93c8045a130a.png)
Your twilio account is not upgraded.

**Comment by d0p3r0b0t** [comment]
![image](https://user-images.githubusercontent.com/89112428/133913088-83f84c16-066f-4747-a640-51b646cee6d6.png)



whats this mean

**Comment by Ross1337** [comment]
Your account has been suspended.
