### ISSUE TITLE
 Uncaught AssertionError: expected { Object (error) } to not have property 'error'

### ISSUE THREAD

**Issue by wantedboy** [Ross1337/SMSBotBypass#60]
1) it should return the callSid : everything's fine
Having this problem my twilio account is upgraded
discord Necro#8991

**Comment by SmellySmel** [comment]
i can help you i added you

**Comment by d0p3r0b0t** [comment]
same here.... my discord is d0p3r0b0t

**Comment by Dwarkhins** [comment]
need help same error @SmellySmel

**Comment by Ross1337** [comment]
Hello, I made a push to now show twilio errors in the http response, just use any http packet manager and try to call using your api it'll show you the error.

**Comment by striderkiin** [comment]
Need help too! Kr3tos#6818

Thanks

**Comment by Dwarkhins** [comment]
> same here.... my discord is d0p3r0b0t#1541

I'm having the same problem, do you mind helping me ? thanks

**Comment by Ross1337** [comment]
> > same here.... my discord is d0p3r0b0t#1541
> 
> I'm having the same problem, do you mind helping me ? thanks

Hello, I made a push to now show twilio errors in the http response, just use any http packet manager and try to call using your api it'll show you the error.

**Comment by Whoisitthis** [comment]
> same here.... my discord is d0p3r0b0t#1541

Bro I invite your freand discord, help pls
