### ISSUE TITLE
Actual Ip

### ISSUE THREAD

**Issue by 0xGhostMan** [Ross1337/SMSBotBypass#64]
What you mean by , Your actual ip to run on the web server
And how to do it tell me please
Open the port 1337, and this also how to open

**Comment by Ross1337** [comment]
Ip = your Public IP
Open port = on your router

**Comment by 0xGhostMan** [comment]
@Ross1337 actually i don't have router, i use my mobile data , can i use ngrok or portmap.io instead?
I don't have router and static ip :(

**Comment by AryaP7** [comment]
how do i use ngrok for this programm tho
