### ISSUE TITLE
help with fckng calls

### ISSUE THREAD

**Issue by firstableohh** [Ross1337/SMSBotBypass#65]
Help.
In the discord bot, when I send a call to a number, it does not go. when I write a number from the site, it calls itself. and he doesn't call other numbers. what to do?

**Comment by 0xGhostMan** [comment]
@Ross1337 if we get full tutorial it will be good, because everyone strucked in many places :(

**Comment by firstableohh** [comment]
how to set up TwiML apps correctly

**Comment by Ross1337** [comment]
It's easy to install. If the discord bot isn't sending the call it's due to two problems : bad config.js configuration or a twilio settings. Use the api with insomnia to check the twilio error (on the localhost:1337/call route).

**Comment by firstableohh** [comment]
> It's easy to install. If the discord bot isn't sending the call it's due to two problems : bad config.js configuration or a twilio settings. Use the api with insomnia to check the twilio error (on the localhost:1337/call route).

Help.
In the discord bot, when I send a call to a number, it does not go. when I write a number from the site, it calls itself. and he doesn't call other numbers. what to do?

**Comment by firstableohh** [comment]
![image](https://user-images.githubusercontent.com/63258656/134040657-13f749d7-6e7f-46d4-861e-f4ce694941b1.png)

**Comment by Ross1337** [comment]
You use the wrong method, you need to use post method

**Comment by Ross1337** [comment]
Read the read me
