### ISSUE TITLE
Call sent with script but no otp

### ISSUE THREAD

**Issue by SmellySmel** [Ross1337/SMSBotBypass#66]
please help with this.
i have used the correct webhook and im testing with textnow.com
it calls me and i put in the 6 digit otp and press pound nothing happens i get no otp code
i tried all the simbols and just the code it self and nothing please help.

**Comment by firstableohh** [comment]
(node:10160) UnhandledPromiseRejectionWarning: Error: Only absolute URLs are supported
    at Webhook.send (C:\Users\ХУНГ\SMSBotBypass\api\node_modules\discord-webhook-node\src\classes\webhook.js:74:41)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SmellySmel** [comment]
yes i have done that i have fixed that but now im getting this in my calls
instead of the script bieng played out it says "were sorry but a appication error has occured"

**Comment by Ross1337** [comment]
Is your port 1337 open ?
