### ISSUE TITLE
Doesn't play the voice

### ISSUE THREAD

**Issue by paungabriel1** [Ross1337/SMSBotBypass#69]
It's calling to me, but it just says "an application error has occurred, goodbye" and call is ends.
What's the problem in?

**Comment by Ross1337** [comment]
Is your port 1337 open ?

**Comment by Ross1337** [comment]
Or your using a VPN ?

**Comment by paungabriel1** [comment]
> Or your using a VPN ?

Im using RDP

**Comment by paungabriel1** [comment]
> Is your port 1337 open ?

It's opening autimaticly, but im trying to call on US numbers

**Comment by Ross1337** [comment]
When you're doing the npm test is there any error ?

**Comment by paungabriel1** [comment]
![image](https://user-images.githubusercontent.com/91350962/134771748-67c62b60-8aff-4b9e-b83b-4a69dd2372fd.png)

**Comment by paungabriel1** [comment]
> When you're doing the npm test is there any error ?



> When you're doing the npm test is there any error ?

https://vimeo.com/614437258

**Comment by paungabriel1** [comment]
Errors log in Twillio
![image](https://user-images.githubusercontent.com/91350962/134772734-f066cc65-7efd-4ff5-a249-abd25a584017.png)
![image](https://user-images.githubusercontent.com/91350962/134772792-79549478-854a-4307-8901-10da16720900.png)
![image](https://user-images.githubusercontent.com/91350962/134772811-6221fee9-0d13-4ba7-86a8-60a3398f233d.png)

**Comment by paungabriel1** [comment]
Sorry, it's was my bad, cuz i forgot to open port
Thank you)

**Comment by paungabriel1** [comment]
Do you know how i can hide a callerId?

**Comment by Ross1337** [comment]
No idea.
