### ISSUE TITLE
Bot disscord  does not work

### ISSUE THREAD

**Issue by Whoisitthis** [Ross1337/SMSBotBypass#71]
hi, my bot discord does not respond to everything except!help, how to be

**Comment by Whoisitthis** [comment]
the command returns an error on ssh

**Comment by Ross1337** [comment]
Is your call api working ?

**Comment by Whoisitthis** [comment]
> Is your call api working ?

Ye

**Comment by Whoisitthis** [comment]
.the api that is on the way.. /api 'npm test' it this

**Comment by paungabriel1** [comment]
> Is your call api working ?

how can i contact you in telegram or discord, i need a private order

**Comment by Rchie67** [comment]
> Is your call api working ?

Ross...please I need something done...do you have telegram or sum

**Comment by Whoisitthis** [comment]
> Ross...please I need something done...do you have telegram or sum

а ну пошли прочь отсюда негодники, хватит спамить
Get out of here, you scoundrels, that's enough

> > Is your call api working ?
> 
> how can i contact you in telegram or discord, i need a private order

**Comment by Whoisitthis** [comment]
> .the api that is on the way.. /api 'npm test' it this ?

calls go through, the voice works fine, but there is still no lag in the discord bot, and do I need to specify something in the extensions TWiLM

**Comment by Ross1337** [comment]
Give me all your telegrams here, I'll add you. I can't support each people on only one github issue.

**Comment by Whoisitthis** [comment]
> Give me all your telegrams here, I'll add you. I can't support each people on only one github issue.

@Whoisitthis

**Comment by Orau25** [comment]
Telegram @iamthene

**Comment by paungabriel1** [comment]
> Give me all your telegrams here, I'll add you. I can't support each people on only one github issue.
can you make private order for me bot like that but with plivo.com?

**Comment by Ross1337** [comment]
> > Give me all your telegrams here, I'll add you. I can't support each people on only one github issue.
> > can you make private order for me bot like that but with plivo.com?

Give me your telegram

**Comment by paungabriel1** [comment]
> > > Give me all your telegrams here, I'll add you. I can't support each people on only one github issue.
> > > can you make private order for me bot like that but with plivo.com?
> 
> Give me your telegram

@tiger_opasniy
