### ISSUE TITLE
commands don't work

### ISSUE THREAD

**Issue by Mood8** [Ross1337/SMSBotBypass#72]
Hello

trying to run commands like: !call 3312345678 paypal
and I get this error, please tell me what I need to fix

  I will be very grateful for the answer

(node:9543) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/root/SMSBotBypass/bots/discord/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.setup (/root/SMSBotBypass/bots/discord/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
    at new MessageEmbed (/root/SMSBotBypass/bots/discord/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/root/SMSBotBypass/bots/discord/node_modules/discord.js/src/structures/APIMessage.js:166:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/root/SMSBotBypass/bots/discord/node_modules/discord.js/src/structures/APIMessage.js:166:31)
    at TextChannel.send (/root/SMSBotBypass/bots/discord/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at embed (/root/SMSBotBypass/bots/discord/embed.js:17:17)
    at Statement.db.get (/root/SMSBotBypass/bots/discord/bot.js:119:11)
    at Statement.replacement (/root/SMSBotBypass/bots/discord/node_modules/sqlite3/lib/trace.js:25:27)
(node:9543) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9543) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Ross1337** [comment]
In the first time, is your npm test working ?

**Comment by Mood8** [comment]
Yes  
npm test working  fine

**Comment by Mood8** [comment]
I changed line 122 in the test to my number and now it gives me such a mistake


  App.js
    test the APP routes
      ✓ test /voice/ : we are looking for a 200 status
      ✓ test /get/ : we are looking for a 200 status
      ✓ test /sms/ : we are looking for a 200 status (729ms)
      ✓ test /status/ : we are looking for a 200 status
      ✓ test /stream/default : we are looking for a 200 status
      ✓ test /call/ : we are looking for a 200 status

  Authentification.js
    /get POST to check authentification.js middleware
      ✓ it should return "Please send the password API." : we are not sending any password post
      ✓ it should return "The password you sent is empty." : we are not sending an empty password
      ✓ it should return "Invalid password." : we are sending a bad password
      ✓ it should return be good : no error

  Call.js
    /call POST
      ✓ it should return an ERROR with "Please post all the informations needed." : we sent no post data
      ✓ it should return an ERROR with "Please post all the informations needed." : we sent 1 post data
      ✓ it should return an ERROR with "Please post all the informations needed." : we sent 2 post data
      ✓ it should return an ERROR with "The service wasn't recognised." : we sent 3 post data (but bad service)
      ✓ it should return an ERROR with "Bad phone number." : we sent 3 post data (but bad phone number)
      1) it should return the callSid : everything's fine

  Config.js
    twilio INFORMATIONS
      ✓ checking the twilio logins using the api : should allow to use it
    api INFORMATIONS
      ✓ check the api password
    services FILEPATH
      ✓ check the services FILEPATH and if the files exists

  Get.js
    /get POST
      ✓ it should return "Invalid callSid." : we are not sending any callSid
      ✓ it should return "Invalid callSid." : we are sending a bad callSid
      ✓ it should return the call info's : we are sending a good callSid

  Voice.js
    /voice POST
      ✓ it should return an ERROR "Please give us the callSid." : we are not sending any callSid
      ✓ it should return the twiML code for the paypal service : we are not sending any callSid or digit
      ✓ it should return the twiML code for the default service : the service is not precised in the db
      ✓ it should return the twiML code for the default service : the service asked doesn't exist
      ✓ it should return the twiML code for the end service : we provided the 6 digits code


  26 passing (2s)
  1 failing

  1) Call.js
       /call POST
         it should return the callSid : everything's fine:
     Uncaught AssertionError: expected { Object (error) } to not have property 'error'
      at chai.request.post.set.send.end (test/call.js:129:46)
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:716:12)
      at parser (node_modules/superagent/lib/node/index.js:916:18)
      at IncomingMessage.res.on (node_modules/superagent/lib/node/parsers/json.js:19:7)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)



npm ERR! Test failed.  See above for more details.

**Comment by Ross1337** [comment]
Is your twilio account upgraded ?

**Comment by Mood8** [comment]
yes, the account has been updated and the balance has been replenished
when i leave the phone unchanged by default the test goes well

phone of any country can be entered?

**Comment by Ross1337** [comment]
Hello, when does this error came ? When submiting a command / call ?

**Comment by Mood8** [comment]
yes when you give the command! call

**Comment by Ross1337** [comment]
Is the call sended ?

**Comment by Mood8** [comment]
no call sended 
immediately gives an error when I send the command to call through the bot

test call will pass successfully

**Comment by Mood8** [comment]
I filled in correctly  config.js. ?
![Снимок экрана 2021-09-30 в 15 46 31](https://user-images.githubusercontent.com/91456179/135458212-0bdc8c48-5600-47e9-afae-ce2686b5c1d6.png)

**Comment by Ross1337** [comment]
Yep, have you done the npm i for the discord bot ? If yes, give me your telegram

**Comment by Mood8** [comment]
yes i did it

telegram: @Sepp888
