### ISSUE TITLE
Stuck at the final step

### ISSUE THREAD

**Issue by Toolie7** [Ross1337/SMSBotBypass#73]
![SMS bot ticket](https://user-images.githubusercontent.com/89987703/134889192-8eb6fc58-8ff0-4633-9fbd-451cea3bc9fb.PNG)

**Comment by Toolie7** [comment]
Im using Discord developer portal to get my token, have been trying for hours on this same step. Am I getting the wrong token? If so where would I get that. If the token is not the issue I dont know what it would be.

**Comment by Ross1337** [comment]
https://discord.com/developers/applications : Here you can create a discord bot, 
![image](https://user-images.githubusercontent.com/45340378/134929944-b8bfe2c9-3c99-4061-ad27-172017394de7.png)
![image](https://user-images.githubusercontent.com/45340378/134930015-317805eb-c37e-4b94-9de3-1c3d62ffc0a8.png)

**Comment by Toolie7** [comment]
I tried that as well and Im still stuck. Same thing from the screenshot above Not sure what to do from here if you can help I would really appreciate it. I try trial and error before asking anything so you know. But cant seem to get passed this.

**Comment by Toolie7** [comment]
Okay I figured out how to get the bot on one of my discord channels with the developer portal. Do I need the webhook? Also where does the bot token go? I cant find it on the config file.

**Comment by Ross1337** [comment]
The webhook is needed for the api config.js file, the discord bot token is needed in the discord bot config.js file

**Comment by Toolie7** [comment]
awesome that helped alot now the discord bot is working. I tried doing the calls says call sent but Im not receiving any calls

**Comment by Toolie7** [comment]
I checked twilio and Im getting an error Invalid url format idk where to go from here

**Comment by Ross1337** [comment]
Send your config.js, I think you badly configured your file

**Comment by Toolie7** [comment]
![config](https://user-images.githubusercontent.com/89987703/135384972-c7e05c3c-40ab-4f12-8ddf-8c8d7e0cc2be.PNG)
![Capture](https://user-images.githubusercontent.com/89987703/135385011-0690a717-18f6-4dd5-930d-f8ab4b9aaaa5.PNG)

**Comment by Toolie7** [comment]
Im going to show you the error Im getting on twilio as well

**Comment by Toolie7** [comment]
![twilio 1](https://user-images.githubusercontent.com/89987703/135385248-d59617b8-53c4-4f27-aa56-32785c624469.PNG)
![twilio 2](https://user-images.githubusercontent.com/89987703/135385251-91a2f467-3cfc-410c-bc5b-375209741e21.PNG)

**Comment by Toolie7** [comment]
I have three different errors on twilio and its that same error code 11100

**Comment by Ross1337** [comment]
Your server URL and API url's are not good's, here is the error

**Comment by Toolie7** [comment]
I tried fixing those and double checked but Im still stuck with the same issue. Would you be able to walk me through or give any kind of info to get it step by step. I tried for a couple hours today still cant get it.

**Comment by Toolie7** [comment]
This is my telegram if you have one @AllegedMurderrr

**Comment by Ross1337** [comment]
Done

**Comment by pizzadaking** [comment]
help @Ross1337 @pizzadaking telegram please :D

**Comment by Ross1337** [comment]
Done

**Comment by darkhacknet** [comment]
> Your server URL and API url's are not good's, here is the error

Bro, I think that in the server URL, the correct is to set the public ip, am I right ? 
And in the API url I really don´t know.... I think that I have the same error due to my bot send the call but nothing else happens ! 

Would you be so kind to help just a little?
Thanks in advance ;)

**Comment by Ross1337** [comment]
Api url = server url = publicip:port

**Comment by darkhacknet** [comment]
> Api url = server url = publicip:port

That's clear for me but not in the part of server URL..
Which is the server URL?

**Comment by darkhacknet** [comment]
> Api url = server url = publicip:port

OK I was good with this.. 👌

**Comment by darkhacknet** [comment]
> Send screens of your config.js files here

Here you have both files bro.

![IMG_20211011_124047.jpg](https://user-images.githubusercontent.com/45680149/136832602-931813e9-d47a-4db5-9057-d2c9dc08a7e4.jpg)

![IMG_20211011_124111.jpg](https://user-images.githubusercontent.com/45680149/136832461-79399f7e-1fe0-405a-bce5-35ec2efd7651.jpg)

**Comment by Ross1337** [comment]
Is the bot sending a new message in your channel ?
