### ISSUE TITLE
data: { error: 'Please send the password API.' }

### ISSUE THREAD

**Issue by gamingman1234** [Ross1337/SMSBotBypass#85]
What am I supposed to do with the API?
I don't understand how this is supposed to call the phone
I am running the server, but what am I supposed to do?

**Comment by gamingman1234** [comment]
I am attempting to call a phone, but I get that error
 data: { error: 'Please send the password API.' }

 _header: 'POST /call/ HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Content-Length: 68\r\n' +
        'Host: localhost:1337\r\n' +
        'Connection: close\r\n' +
        '\r\n',

**Comment by Ross1337** [comment]
You need to setup the discord bot and call using the discord bot, the api is used to send the calls, the discord bot to use the api

**Comment by gamingman1234** [comment]
Ok @ross1337 but how do I get the API to use? Is it twilio? If so how can I proceed? Theres no explanation

**Comment by gamingman1234** [comment]
Now I get error
    data: { error: 'Invalid password.' }

**Comment by Ross1337** [comment]
All the explanations are on the readme? You need to use the discord bot in order to send the calls
