### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by Oliverhunt204** [Ross1337/SMSBotBypass#93]
i do npm i and get this 

npm i
: Permission denieds/nodejs/npm: 3:
: Permission denieds/nodejs/npm: 5:
/mnt/c/Program Files/nodejs/npm: 6: Syntax error: word unexpected (expecting "in")

**Comment by Ross1337** [comment]
Hello, are you using a vps ?

**Comment by Oliverhunt204** [comment]
no

**Comment by Ross1337** [comment]
What is your os ?

**Comment by Oliverhunt204** [comment]
windows using kali linux app to run the commands

**Comment by Ross1337** [comment]
Just use sudo in front of your commands, or learn how linux os works
