### ISSUE TITLE
could you help me pls.  Iam really want to test your code. 

### ISSUE THREAD

**Issue by tutkaktut2020** [Ross1337/SMSBotBypass#96]
Hi
could you help me pls?.  Iam really want to test your code. But I noob in this. 
Better if u text me in telegram  @kubrubi
I have got this mistake: 
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/91866681/136696997-6cf9ff46-b7bb-4267-ab03-d6f7dd837740.png">
And I don't understand what I need to do next.
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/91866681/136697777-3f39e342-f007-472c-b253-402a45691d31.png">

Thank you in advance

**Comment by tutkaktut2020** [comment]
next problem) 
<img width="937" alt="image" src="https://user-images.githubusercontent.com/91866681/136705516-fea33b2c-d87c-42fa-b190-90959041323c.png">

**Comment by Ross1337** [comment]
Have you read the readme ?
